#
# Copyright 2025 LinQingYing. and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# The use of this source code is governed by the Apache License 2.0,
# which allows users to freely use, modify, and distribute the code,
# provided they adhere to the terms of the license.
#
# The software is provided "as-is", and the authors are not responsible for
# any damages or issues arising from its use.
#
#
org.gradle.parallel=true
#org.gradle.configuration-cache=true
kotlin.incremental=true
kotlin.caching.enabled=true
propertiesPluginEnvironmentNameProperty=platformVersion
platformVersion=243
baseIDE=IC
ideToRunType=


pluginVersion=1.0.7
sinceBuild=243
untilBuild=253.*
versionSuffix=

channel=nightly


showTestStatus=false
showStandardStreams=false
enableBuildSearchableOptions=false
compileNativeCode=true
org.gradle.jvmargs=-Xmx3g
# Enable Gradle Build Cache. It is also configured in settings.gradle.kts.
org.gradle.caching=true
systemProp.org.gradle.internal.repository.max.tentatives=10
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
systemProp.org.gradle.internal.http.sslVerify=false
# Since kotlin 1.4, stdlib dependency is added by default by kotlin gradle plugin.
# But we don't need it because all necessary kotlin libraries are already bundled into IDE.
# See https://kotlinlang.org/docs/reference/using-gradle.html#dependency-on-the-standard-library for more details
kotlin.stdlib.default.dependency=false
# Since kotlin 1.8.20, Gradle Kotlin plugin may produce OOM during compilation
# See https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#incremental-compilation
# and https://youtrack.jetbrains.com/issue/KT-57757 for more details




