// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metadata/src/ext_options.proto
// Protobuf Java Version: 4.27.2

package com.huawei.cangjie.metadata;

public final class ExtOptionsProtoBuf {
  private ExtOptionsProtoBuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ExtOptionsProtoBuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.huawei.cangjie.metadata.ExtOptionsProtoBuf.skipInComparison);
    registry.add(com.huawei.cangjie.metadata.ExtOptionsProtoBuf.nameIdInTable);
    registry.add(com.huawei.cangjie.metadata.ExtOptionsProtoBuf.fqNameIdInTable);
    registry.add(com.huawei.cangjie.metadata.ExtOptionsProtoBuf.stringIdInTable);
    registry.add(com.huawei.cangjie.metadata.ExtOptionsProtoBuf.typeIdInTable);
    registry.add(com.huawei.cangjie.metadata.ExtOptionsProtoBuf.skipMessageInComparison);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int SKIP_IN_COMPARISON_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> skipInComparison = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int NAME_ID_IN_TABLE_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> nameIdInTable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int FQ_NAME_ID_IN_TABLE_FIELD_NUMBER = 50002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> fqNameIdInTable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int STRING_ID_IN_TABLE_FIELD_NUMBER = 50003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> stringIdInTable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int TYPE_ID_IN_TABLE_FIELD_NUMBER = 50004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> typeIdInTable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int SKIP_MESSAGE_IN_COMPARISON_FIELD_NUMBER = 50100;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> skipMessageInComparison = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036metadata/src/ext_options.proto\022\033com.hu" +
      "awei.cangjie.metadata\032 google/protobuf/d" +
      "escriptor.proto:;\n\022skip_in_comparison\022\035." +
      "google.protobuf.FieldOptions\030\320\206\003 \001(\010:9\n\020" +
      "name_id_in_table\022\035.google.protobuf.Field" +
      "Options\030\321\206\003 \001(\010:<\n\023fq_name_id_in_table\022\035" +
      ".google.protobuf.FieldOptions\030\322\206\003 \001(\010:;\n" +
      "\022string_id_in_table\022\035.google.protobuf.Fi" +
      "eldOptions\030\323\206\003 \001(\010:9\n\020type_id_in_table\022\035" +
      ".google.protobuf.FieldOptions\030\324\206\003 \001(\010:E\n" +
      "\032skip_message_in_comparison\022\037.google.pro" +
      "tobuf.MessageOptions\030\264\207\003 \001(\010B\024B\022ExtOptio" +
      "nsProtoBuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    skipInComparison.internalInit(descriptor.getExtensions().get(0));
    nameIdInTable.internalInit(descriptor.getExtensions().get(1));
    fqNameIdInTable.internalInit(descriptor.getExtensions().get(2));
    stringIdInTable.internalInit(descriptor.getExtensions().get(3));
    typeIdInTable.internalInit(descriptor.getExtensions().get(4));
    skipMessageInComparison.internalInit(descriptor.getExtensions().get(5));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
