// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metadata/src/properties_order_extension.proto
// Protobuf Java Version: 4.27.2

package com.huawei.cangjie.metadata;

public final class SerializationPluginMetadataExtensions {
  private SerializationPluginMetadataExtensions() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      SerializationPluginMetadataExtensions.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.huawei.cangjie.metadata.SerializationPluginMetadataExtensions.propertiesNamesInProgramOrder);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int PROPERTIES_NAMES_IN_PROGRAM_ORDER_FIELD_NUMBER = 18000;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Class { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Class,
      java.util.List<java.lang.Integer>> propertiesNamesInProgramOrder = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-metadata/src/properties_order_extensio" +
      "n.proto\022\033com.huawei.cangjie.metadata\032\033me" +
      "tadata/src/metadata.proto\032\036metadata/src/" +
      "ext_options.proto:O\n!properties_names_in" +
      "_program_order\022\".com.huawei.cangjie.meta" +
      "data.Class\030\320\214\001 \003(\005B\'B%SerializationPlugi" +
      "nMetadataExtensions"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.huawei.cangjie.metadata.ProtoBuf.getDescriptor(),
          com.huawei.cangjie.metadata.ExtOptionsProtoBuf.getDescriptor(),
        });
    propertiesNamesInProgramOrder.internalInit(descriptor.getExtensions().get(0));
    descriptor.resolveAllFeaturesImmutable();
    com.huawei.cangjie.metadata.ProtoBuf.getDescriptor();
    com.huawei.cangjie.metadata.ExtOptionsProtoBuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
