package com.huawei.cangjie.descriptors

import com.huawei.cangjie.diagnostics.Severity
import com.huawei.cangjie.resolve.BindingContext
import com.huawei.cangjie.utils.ExtensionProvider
import com.intellij.openapi.extensions.ExtensionPointName
import com.intellij.psi.PsiElement


abstract class CangJieSuppressCache : AbstractCangJieSuppressCache<PsiElement>(){
    private val diagnosticSuppressors = ExtensionProvider.create(DiagnosticSuppressor.EP_NAME)
    protected open fun isSuppressedByExtension(suppressor: DiagnosticSuppressor, diagnostic: Diagnostic): Boolean {
        return suppressor.isSuppressed(diagnostic)
    }

//    override fun getClosestAnnotatedAncestorElement(element: PsiElement, rootElement: PsiElement, excludeSelf: Boolean): PsiElement? =
//        CjStubbedPsiUtil.getPsiOrStubParent(element, CjAnnotated::class.java, excludeSelf)
//
//    private fun processAnnotation(builder: ImmutableSet.Builder<String>, annotationDescriptor: AnnotationDescriptor) {
//        if (annotationDescriptor.fqName != StandardNames.FqNames.suppress) return
//
//        // We only add strings and skip other values to facilitate recovery in presence of erroneous code
//        for (arrayValue in annotationDescriptor.allValueArguments.values) {
//            if (arrayValue is ArrayValue) {
//                for (value in arrayValue.value) {
//                    if (value is StringValue) {
//                        builder.add(value.value.lowercase())
//                    }
//                }
//            }
//        }
//    }
//    abstract fun getSuppressionAnnotations(annotated: PsiElement): List<AnnotationDescriptor>
//
//    override fun getSuppressingStrings(annotated: PsiElement): Set<String> {
//        val builder = ImmutableSet.builder<String>()
//
//        for (annotationDescriptor in getSuppressionAnnotations(annotated)) {
//            processAnnotation(builder, annotationDescriptor)
//        }
//
//        return builder.build()
//    }
//    override fun isSuppressed(request: SuppressRequest<PsiElement>): Boolean {
//        // If diagnostics are reported in a synthetic file generated by KtPsiFactory (dummy.kt),
//        // there's no point to present such diagnostics to the user, because the user didn't write this code
//        val element = request.element
//        if (!element.isValid) return true
//
//        val file = element.containingFile
//        if (file is CjFile) {
//            if (file.doNotAnalyze != null) return true
//        }
//
//        if (request is DiagnosticSuppressRequest) {
//            for (suppressor in diagnosticSuppressors.get()) {
//                if (isSuppressedByExtension(suppressor, request.diagnostic)) return true
//            }
//        }
//        return super.isSuppressed(request)
//    }

//    val filter: (Diagnostic) -> Boolean = { diagnostic: Diagnostic ->
//        !isSuppressed(DiagnosticSuppressRequest(diagnostic))
//    }


    companion object {
        internal fun getDiagnosticSuppressKey(diagnostic: Diagnostic): String =
            diagnostic.factory.name.lowercase()
    }
    protected class DiagnosticSuppressRequest(val diagnostic: Diagnostic) : SuppressRequest<PsiElement> {
        override val element: PsiElement get() = diagnostic.psiElement
        override val rootElement: PsiElement get() = element.containingFile
        override val severity: Severity get() = diagnostic.severity
        override val suppressKey: String get() = getDiagnosticSuppressKey(diagnostic)
    }
}

interface DiagnosticSuppressor {
    fun isSuppressed(diagnostic: Diagnostic): Boolean
    fun isSuppressed(diagnostic: Diagnostic, bindingContext: BindingContext?): Boolean = isSuppressed(diagnostic)

    companion object {
        val EP_NAME: ExtensionPointName<DiagnosticSuppressor> =
            ExtensionPointName.create("com.huawei.cangjie.diagnosticSuppressor")
    }
}

class BindingContextSuppressCache(val context: BindingContext) : CangJieSuppressCache() {
//    override fun getSuppressionAnnotations(annotated: PsiElement): List<AnnotationDescriptor> {
//        val descriptor = context.get(BindingContext.DECLARATION_TO_DESCRIPTOR, annotated)
//
//        return descriptor?.annotations?.toList()
//            ?: (annotated as? KtAnnotated)?.annotationEntries?.mapNotNull { context.get(BindingContext.ANNOTATION, it) }
//            ?: emptyList()
//    }

    override fun isSuppressedByExtension(suppressor: DiagnosticSuppressor, diagnostic: Diagnostic): Boolean {
        return suppressor.isSuppressed(diagnostic, context)
    }




}

