// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metadata/src/builtins.debug.proto
// Protobuf Java Version: 4.27.2

package com.huawei.cangjie.metadata.builtins;

public final class DebugBuiltInsProtoBuf {
  private DebugBuiltInsProtoBuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      DebugBuiltInsProtoBuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.packageFqName);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.classAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.constructorAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.functionAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.propertyAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.propertyGetterAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.propertySetterAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.compileTimeValue);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.enumEntryAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.parameterAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.typeAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.DebugBuiltInsProtoBuf.typeParameterAnnotation);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int PACKAGE_FQ_NAME_FIELD_NUMBER = 151;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Package { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Package,
      java.lang.Integer> packageFqName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int CLASS_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Class { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Class,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> classAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int CONSTRUCTOR_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Constructor { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Constructor,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> constructorAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int FUNCTION_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Function { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Function,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> functionAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int PROPERTY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Property,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> propertyAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int PROPERTY_GETTER_ANNOTATION_FIELD_NUMBER = 152;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Property,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> propertyGetterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int PROPERTY_SETTER_ANNOTATION_FIELD_NUMBER = 153;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Property,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> propertySetterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int COMPILE_TIME_VALUE_FIELD_NUMBER = 151;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Property,
      com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.Argument.Value> compileTimeValue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.Argument.Value.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.Argument.Value.getDefaultInstance());
  public static final int ENUM_ENTRY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.EnumEntry { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.EnumEntry,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> enumEntryAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.ValueParameter { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.ValueParameter,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> parameterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int TYPE_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Type { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.Type,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> typeAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());
  public static final int TYPE_PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.TypeParameter { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.DebugProtoBuf.TypeParameter,
      java.util.List<com.huawei.cangjie.metadata.DebugProtoBuf.Annotation>> typeParameterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.DebugProtoBuf.Annotation.getDefaultInstance());

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!metadata/src/builtins.debug.proto\022$com" +
      ".huawei.cangjie.metadata.builtins\032!metad" +
      "ata/src/metadata.debug.proto:>\n\017package_" +
      "fq_name\022$.com.huawei.cangjie.metadata.Pa" +
      "ckage\030\227\001 \001(\005:f\n\020class_annotation\022\".com.h" +
      "uawei.cangjie.metadata.Class\030\226\001 \003(\0132\'.co" +
      "m.huawei.cangjie.metadata.Annotation:r\n\026" +
      "constructor_annotation\022(.com.huawei.cang" +
      "jie.metadata.Constructor\030\226\001 \003(\0132\'.com.hu" +
      "awei.cangjie.metadata.Annotation:l\n\023func" +
      "tion_annotation\022%.com.huawei.cangjie.met" +
      "adata.Function\030\226\001 \003(\0132\'.com.huawei.cangj" +
      "ie.metadata.Annotation:l\n\023property_annot" +
      "ation\022%.com.huawei.cangjie.metadata.Prop" +
      "erty\030\226\001 \003(\0132\'.com.huawei.cangjie.metadat" +
      "a.Annotation:s\n\032property_getter_annotati" +
      "on\022%.com.huawei.cangjie.metadata.Propert" +
      "y\030\230\001 \003(\0132\'.com.huawei.cangjie.metadata.A" +
      "nnotation:s\n\032property_setter_annotation\022" +
      "%.com.huawei.cangjie.metadata.Property\030\231" +
      "\001 \003(\0132\'.com.huawei.cangjie.metadata.Anno" +
      "tation:z\n\022compile_time_value\022%.com.huawe" +
      "i.cangjie.metadata.Property\030\227\001 \001(\01326.com" +
      ".huawei.cangjie.metadata.Annotation.Argu" +
      "ment.Value:o\n\025enum_entry_annotation\022&.co" +
      "m.huawei.cangjie.metadata.EnumEntry\030\226\001 \003" +
      "(\0132\'.com.huawei.cangjie.metadata.Annotat" +
      "ion:s\n\024parameter_annotation\022+.com.huawei" +
      ".cangjie.metadata.ValueParameter\030\226\001 \003(\0132" +
      "\'.com.huawei.cangjie.metadata.Annotation" +
      ":d\n\017type_annotation\022!.com.huawei.cangjie" +
      ".metadata.Type\030\226\001 \003(\0132\'.com.huawei.cangj" +
      "ie.metadata.Annotation:w\n\031type_parameter" +
      "_annotation\022*.com.huawei.cangjie.metadat" +
      "a.TypeParameter\030\226\001 \003(\0132\'.com.huawei.cang" +
      "jie.metadata.AnnotationB\027B\025DebugBuiltIns" +
      "ProtoBuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.huawei.cangjie.metadata.DebugProtoBuf.getDescriptor(),
        });
    packageFqName.internalInit(descriptor.getExtensions().get(0));
    classAnnotation.internalInit(descriptor.getExtensions().get(1));
    constructorAnnotation.internalInit(descriptor.getExtensions().get(2));
    functionAnnotation.internalInit(descriptor.getExtensions().get(3));
    propertyAnnotation.internalInit(descriptor.getExtensions().get(4));
    propertyGetterAnnotation.internalInit(descriptor.getExtensions().get(5));
    propertySetterAnnotation.internalInit(descriptor.getExtensions().get(6));
    compileTimeValue.internalInit(descriptor.getExtensions().get(7));
    enumEntryAnnotation.internalInit(descriptor.getExtensions().get(8));
    parameterAnnotation.internalInit(descriptor.getExtensions().get(9));
    typeAnnotation.internalInit(descriptor.getExtensions().get(10));
    typeParameterAnnotation.internalInit(descriptor.getExtensions().get(11));
    descriptor.resolveAllFeaturesImmutable();
    com.huawei.cangjie.metadata.DebugProtoBuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
