// Copyright 2000-2023 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
package com.linqingying.cangjie.ide.completion.turboComplete

import org.jetbrains.annotations.ApiStatus

/**
 * An interface for classes that consume suggestion generators,
 * generated by [KindCollector]
 */

interface SuggestionGeneratorConsumer {
  fun pass(suggestionGenerator: SuggestionGenerator)
}