/*
 * Copyright 2026 LinQingYing. and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * The use of this source code is governed by the Apache License 2.0,
 * which allows users to freely use, modify, and distribute the code,
 * provided they adhere to the terms of the license.
 *
 * The software is provided "as-is", and the authors are not responsible for
 * any damages or issues arising from its use.
 *
 */

package org.cangnova.cangjie.completion.turboComplete

import com.intellij.codeInsight.completion.CompletionParameters
import com.intellij.codeInsight.completion.CompletionResultSet


/**
 * Collects all [SuggestionGenerator] of the same variety,
 * without executing them.
 *
 * The purpose of this class it to just acknowledge existence of
 * the generators, so then we can reorder the generators, and
 * run them in the order we want.
 */

interface KindCollector {
  /**
   * The variety of completion suggestions generated by collected [SuggestionGenerator]s
   *
   * An analogue of [com.intellij.codeInsight.completion.CompletionContributor],
   * but instead of executing all suggestion generators immediately, it delegates their execution
   */
  val kindVariety: KindVariety

  /**
   * Checks if this collector is relevant within the given parameters
   */
  fun shouldBeCalled(parameters: CompletionParameters): Boolean

  /**
   * Collects and adds [SuggestionGenerator]s to the consumer
   *
   * An analogue of [com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants]
   *
   * @param parameters The completion parameters containing information about the current completion request.
   * @param generatorExecutor The suggestion generator consumer used to collect [SuggestionGenerator]s.
   * @param result The completion result set to which the suggestions will be added.
   */
  fun collectKinds(parameters: CompletionParameters,
                   generatorExecutor: SuggestionGeneratorExecutor,
                   result: CompletionResultSet)
}