{
    parserClass='com.huawei.cangjie.lang.core.parser.CangJieParser'

    parserUtilClass='com.huawei.cangjie.lang.core.parser.CangJieParserUtil'

    implements='com.huawei.cangjie.lang.core.psi.ext.CjElement'
    extends='com.huawei.cangjie.lang.core.psi.ext.CjElementImpl'
//extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
   psiClassPrefix="CangJie"
   psiImplClassSuffix="Impl"
   psiPackage="com.huawei.cangjie.lang.core.psi"
   psiImplPackage="com.huawei.cangjie.lang.core.psi.impl"
  elementTypePrefix=""
   elementTypeHolderClass="com.huawei.cangjie.lang.core.psi.CjElementTypes"
   elementTypeClass="com.huawei.cangjie.lang.core.psi.CjTokenType"
   tokenTypeClass="com.huawei.cangjie.lang.core.psi.CjTokenType"

 tokenTypeClass="com.huawei.cangjie.lang.core.psi.CjElementTypes"

    tokens = [
//    关键字
        MAIN            =   'main'
        FUNC            =   'func'
        CLASS           =   'class'
        VAR             =   'var'
        LET             =   'let'
        MUT             =   'mut'
        PROP            =   'prop'
        INIT            =   'init'
        OPEN            =   'open'
        FROM            =   'from'
        IMPORT          =   'import'
        AS              =   'as'
        ENUM            =   'enum'
        SUPER           =   'super'
        THIS            =   'this'
        INTERFACE       =   'interface'
        STATIC          =   'static'
        STRUCT          =   'struct'
        RETURN          =   'return'

//扩展关键字
        EXTEND          =   'extend'


        //值
        TRUE            =   'true'
        FALSE           =   'false'

        //基本类型
        INT8            =   'Int8'
        INT16           =   'Int16'
        INT32           =   'Int32'
        INT64           =   'Int64'
        FLOAT32         =   'Float32'
        FLOAT64         =   'Float64'
        CHAE            =   'Char'
        UINT8           =   'UInt8'
        UINT16          =   'UInt16'
        UINT32          =   'UInt32'
        UINT64          =   'UInt64'
        BOOL            =   'Bool'
        UNIT            =   'Unit'



//流程控制

        IF              =   'if'
        ELSE            =   'else'
        WHILE           =   'while'
        FOR             =   'for'
        IN              =   'in'
        DO              =   'do'
        BREAK           =   'break'
        CONTINUE        =   'continue'
        MATCH           =   'match'
        CASE            =   'case'




        TRY             =   'try'
        CATCH           =   'catch'
        FINALLY         =   'finally'
        THROW           =   'throw'




        LBRACE      =  '{'
         RBRACE      =  '}'
         LBRACK      =  '['
         RBRACK      =  ']'
         LPAREN      =  '('
         RPAREN      =  ')'


         //操作符
            EQ          =   '='



            EQEQ        =   '=='
            NOTEQ       =   '!='
            GT          =   '>'
            GTGT        =   '>>'


            LT          =   '<'
            LTLT        =   '<<'

            GTEQ        =   '>='
            LTEQ        =   '<='

            ANDAND      =   '&&'
            AND         =   '&'
            OROR        =   '||'
            OR          =   '|'

 ]
// extends("(.+Expr)") = Expr
  generateTokenAccessors=true


   extraRoot(".*CodeFragmentElement")=true

}


 //自上而下的语法分析器
 //仓颉文件 包含
CangJie ::= RootItems

StatementCodeFragmentElement ::= Stmt?
MainFuncCodeFragmentElement ::= MainFunc?


private  RootItems ::=  RootItem_with_recover*
private RootItem_with_recover ::= !<<eof>> Item    {
  pin = 1

  //语法恢复
//  recoverWhile = RootItem_recover
}



//main方法  一个文件只能出现一次
MainFunc ::= MAIN '(' MainFuncParam? ')' ByType? ShallowBlock ';'?
{
pin =  1

  implements = "com.huawei.cangjie.lang.core.psi.ext.CjItemsOwner"
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjPlaceholderStub<?>"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}
//main方法参数，Array<String>
MainFuncParam ::= 'Array<String>'
//上层  可以包含 函数，类，接口，枚举，结构体，变量，常量，属性,扩展，导入导出语句，注释，main方法
Item ::= ( Function)
{
  name = "item"
//  elementType = ToBeUpped
  hooks = [ leftBinder = "ADJACENT_LINE_COMMENTS" ]
}


//表达式
Expr ::= A

EOL ::=  '\n'   | '\r\n'

//语句 语句可以是表达式，也可以是声明 语句以分号或者回车结束
Stmt ::= (ExprStmt | Item )
private ExprStmt ::= Expr ';'?
private ItemStmt ::= Item ';'?



upper  A ::= 'aa'


upper Function ::= unsafe? FUNC identifier FuncParameters  ByType?    ShallowBlock ';'?
{

pin = 'identifier'
}

FuncParameters ::= '(' !',' ParamStmt*  ')'
{
pin = 1
}

ParamStmt ::= identifier  ByType
{
  pin = 1
  name = 'param'
}





private ByType ::= ':' Type
{
pin = 1
}




//类型  基本类型，自定义类型
Type ::= 'a'
{
  pin = 1
  name = 'type'
}

fake Block ::= '{' (Stmt | Function) *  '}'
{
pin = 1
  implements = "com.huawei.cangjie.lang.core.psi.ext.CjItemsOwner"
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjPlaceholderStub<?>"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}



//SimpleBlock ::= '{'   '}' {
//  pin = 1
//  elementType = Block
//}

//函数体  包含函数定义，和各种表达式
FuncBlock ::= '{'( Function | ExprStmt)*  '}'{
  pin = 1
  elementType = Block
}




private ShallowBlock ::= <<parseCodeBlockLazy>>
//fake ToBeUpped ::=
