{
    parserClass='com.huawei.cangjie.lang.core.parser.CangJieParser'

    parserUtilClass='com.huawei.cangjie.lang.core.parser.CangJieParserUtil'

    implements='com.huawei.cangjie.lang.core.psi.ext.CjElement'
    extends='com.huawei.cangjie.lang.core.psi.ext.CjElementImpl'

   psiClassPrefix="Cj"
   psiImplClassSuffix="Impl"
   psiPackage="com.huawei.cangjie.lang.core.psi"
   psiImplPackage="com.huawei.cangjie.lang.core.psi.impl"

   elementTypeHolderClass="com.huawei.cangjie.lang.core.psi.CjElementTypes"
   elementTypeClass="com.huawei.cangjie.lang.core.psi.CjElementType"
   tokenTypeClass="com.huawei.cangjie.lang.core.psi.CjTokenType"


    parserImports=[
      'static com.huawei.cangjie.lang.core.parser.CangJieParserUtil.PathParsingMode.*'
    ]
    tokens = [

//    关键字
        MAIN            =   'main'
        FUNC            =   'func'
        CLASS           =   'class'
        VAR             =   'var'
        LET             =   'let'
        MUT             =   'mut'
        PROP            =   'prop'
        INIT            =   'init'
        OPEN            =   'open'
        FROM            =   'from'
        IMPORT          =   'import'
        AS              =   'as'
        ENUM            =   'enum'
        SUPER           =   'super'
        THIS            =   'this'
        INTERFACE       =   'interface'
        STATIC          =   'static'
        STRUCT          =   'struct'
        RETURN          =   'return'

//扩展关键字
        EXTEND          =   'extend'


        //值
        TRUE            =   'true'
        FALSE           =   'false'

        //基本类型
        INT8            =   'Int8'
        INT16           =   'Int16'
        INT32           =   'Int32'
        INT64           =   'Int64'
        FLOAT32         =   'Float32'
        FLOAT64         =   'Float64'
        CHAE            =   'Char'
        UINT8           =   'UInt8'
        UINT16          =   'UInt16'
        UINT32          =   'UInt32'
        UINT64          =   'UInt64'
        BOOL            =   'Bool'
        UNIT            =   'Unit'



//流程控制

        IF              =   'if'
        ELSE            =   'else'
        WHILE           =   'while'
        FOR             =   'for'
        IN              =   'in'
        DO              =   'do'
        BREAK           =   'break'
        CONTINUE        =   'continue'
        MATCH           =   'match'
        CASE            =   'case'




        TRY             =   'try'
        CATCH           =   'catch'
        FINALLY         =   'finally'
        THROW           =   'throw'




        LBRACE      =  '{'
         RBRACE      =  '}'
         LBRACK      =  '['
         RBRACK      =  ']'
         LPAREN      =  '('
         RPAREN      =  ')'


         //操作符
            EQ          =   '='



            EQEQ        =   '=='
            NOTEQ       =   '!='
            GT          =   '>'
            GTGT        =   '>>'


            LT          =   '<'
            LTLT        =   '<<'
            GTEQ        =   '>='
            LTEQ        =   '<='
            ANDAND      =   '&&'
            AND         =   '&'
            OROR        =   '||'
            OR          =   '|'

                    DOT         =  '.'
                    DOTDOT      =  '..'



                    //其他

                            SHEBANG_LINE = 'shebang_line'

 ]
    extends("(.+Expr)") = Expr



    elementType("(Func)Parameter") = ValueParameter
    elementType("(Func)Parameters") = ValueParameterList

   extraRoot(".*CodeFragmentElement")=true


    generateTokenAccessors=true

//       consumeTokenMethod("((?!.*_with_recover).*_recover)|(.*_first)|(.*Expr)") = "consumeTokenFast"
}


 //自上而下的语法分析器
 //仓颉文件 包含
CangJie ::= RootItems

StatementCodeFragmentElement ::= Stmt?
//MainFuncCodeFragmentElement ::= MainFunc?
TypeReferenceCodeFragmentElement ::= TypeReference?

private  RootItems ::= RootItem_with_recover*
private RootItem_with_recover ::= !<<eof>> Item    {
  pin = 1

  //语法恢复
  recoverWhile = RootItem_recover
}


private RootItem_recover ::= !Item_first



//元素语法恢复，会将其中的语法解析为一个PsiElement 如果没有这个东西，就会解析成一个字母一个PsiElement
// 比如 struct，有这个东西就会解析成 PsiElement(struct)
// 没有就会解析成6个PsiElement(BAD_CHARACTER)
private Item_first ::= FUNC |   identifier



//main方法  一个文件只能出现一次
MainFunc ::= MAIN '(' MainFuncParam? ')' ByType? ShallowBlock ';'?
{
    pin =  1

  implements = "com.huawei.cangjie.lang.core.psi.ext.CjItemsOwner"
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjPlaceholderStub<?>"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}
//main方法参数，Array<String>
MainFuncParam ::= 'Array<String>'
//上层  可以包含 函数，类，接口，枚举，结构体，变量，常量，属性,扩展，导入导出语句，注释，main方法
Item ::= (MainFunc | Function)
{
  name = "item"
//  elementType = ToBeUpped
  hooks = [ leftBinder = "ADJACENT_LINE_COMMENTS" ]

}

LabelDecl ::= QUOTE_IDENTIFIER ':' {
  implements = [ "com.huawei.cangjie.lang.core.psi.ext.CjNameIdentifierOwner" ]
  mixin = "com.huawei.cangjie.lang.core.psi.ext.CjLabelDeclImplMixin"
}

fake ValueParameter ::= 'a'?  TypeReference? DefaultParameterValue?
{

  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjValueParameterStub"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
 }

DefaultParameterValue ::= '=' ExprStmt {
  pin = 1
  implements = [ "com.huawei.cangjie.lang.core.psi.ext.CjInferenceContextOwner" ]
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjPlaceholderStub<?>"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}






fake ValueParameterList ::=  ValueParameter*   {
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjPlaceholderStub<?>"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}
//表达式
Expr ::= AExpr

//EOL ::=  '\n'   | '\r\n'

//语句 语句可以是表达式，也可以是声明 语句以分号或者回车结束
 Stmt ::= (ExprStmt | Item )
private ExprStmt ::= Expr ';'?
private ItemStmt ::= Item ';'?


//
//IdentifierName ::= identifier
//{
//  pin   =   'identifier'
//  name  =   'name'
//  implements = [
//            "com.huawei.cangjie.lang.core.psi.ext.CjNameIdentifierOwner"
//  ]
//  mixin =   "com.huawei.cangjie.lang.core.psi.ext.CjNamedElementImpl"
//}


upper  AExpr ::= 'abcdefg'


upper Function ::= unsafe? FUNC identifier FuncParameters  ByType?    ShallowBlock ';'?
{
    pin = 'identifier'

    implements = [
        "com.huawei.cangjie.lang.core.psi.ext.CjNameIdentifierOwner"
        "com.huawei.cangjie.lang.core.psi.ext.CjQualifiedNamedElement"

    ]
    extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
    mixin = "com.huawei.cangjie.lang.core.psi.ext.CjFunctionImplMixin"
    stubClass = "com.huawei.cangjie.lang.core.stubs.CjFunctionStub"
    elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"

}

FuncParameters ::= '(' !','  FuncParameter_with_recover*    ')'
{
pin = 1
}

private FuncParameter_with_recover ::= !(')' | '{' | ';') FuncParameter (',' | &')') {
  pin = 1
  recoverWhile = FuncParameter_recover
}
private Pat_first ::=   '&' | '(' | '[' | Path_first | AnyLitToken_first
private Path_first ::= identifier  | super

private FuncParameter_recover ::= !(Pat_first  |   ')' | '{' | ';')
FuncParameter ::=  {'b' ':' } TypeReference DefaultParameterValue?


ParamStmt ::= identifier  ByType
{
  pin = 1
  name = 'param'
}





private ByType ::= ':' TypeReference
{
pin = 1
}




//类型  基本类型，自定义类型
TypeReference ::= 'a'
{
  pin = 1
  name = 'type'
}

fake Block ::= '{' (Stmt | Function) *  '}'
{
pin = 1
  implements = "com.huawei.cangjie.lang.core.psi.ext.CjItemsOwner"
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjPlaceholderStub<?>"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}



//SimpleBlock ::= '{'   '}' {
//  pin = 1
//  elementType = Block
//}

//函数体  包含函数定义，和各种表达式
FuncBlock ::= '{'( Function | ExprStmt)*  '}'{
  pin = 1
  elementType = Block
}


private AnyLitToken ::= STRING_LITERAL | BYTE_STRING_LITERAL | CSTRING_LITERAL
                      | RAW_STRING_LITERAL | RAW_BYTE_STRING_LITERAL | RAW_CSTRING_LITERAL
                      | CHAR_LITERAL | BYTE_LITERAL
                      | FLOAT_LITERAL | <<parseFloatLiteral>> | INTEGER_LITERAL
                      | BOOL_LITERAL {
  consumeTokenMethod = "consumeTokenFast"
}

private AnyLitToken_first ::= STRING_LITERAL | BYTE_STRING_LITERAL | CSTRING_LITERAL
                            | RAW_STRING_LITERAL | RAW_BYTE_STRING_LITERAL | RAW_CSTRING_LITERAL
                            | CHAR_LITERAL | BYTE_LITERAL
                            | FLOAT_LITERAL | INTEGER_LITERAL
                            | BOOL_LITERAL

LifetimeParamBounds ::= ':' Lifetime ('+' Lifetime)* { pin = 1 }

Lifetime ::= QUOTE_IDENTIFIER {
  implements = [ "com.huawei.cangjie.lang.core.psi.ext.CjNameIdentifierOwner"
                 "com.huawei.cangjie.lang.core.psi.ext.CjMandatoryReferenceElement" ]
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  mixin = "com.huawei.cangjie.lang.core.psi.ext.CjLifetimeImplMixin"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjLifetimeStub"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}

LifetimeParameter ::=   QUOTE_IDENTIFIER LifetimeParamBounds? {
  implements = [ "com.huawei.cangjie.lang.core.psi.ext.CjGenericParameter"
                ]
  extends = "com.huawei.cangjie.lang.core.psi.ext.CjStubbedElementImpl<?>"
  mixin = "com.huawei.cangjie.lang.core.psi.ext.CjLifetimeParameterImplMixin"
  stubClass = "com.huawei.cangjie.lang.core.stubs.CjLifetimeParameterStub"
  elementTypeFactory = "com.huawei.cangjie.lang.core.stubs.StubImplementationsKt.factory"
}



private ShallowBlock ::= <<parseCodeBlockLazy>>
//fake ToBeUpped ::=
