/*
 * Copyright 2026 LinQingYing. and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * The use of this source code is governed by the Apache License 2.0,
 * which allows users to freely use, modify, and distribute the code,
 * provided they adhere to the terms of the license.
 *
 * The software is provided "as-is", and the authors are not responsible for
 * any damages or issues arising from its use.
 *
 */

package org.cangnova.cangjie.completion.turboComplete

import com.intellij.codeInsight.completion.CompletionParameters
import com.intellij.codeInsight.completion.CompletionResultSet
import com.intellij.codeInsight.lookup.LookupElement
import com.intellij.openapi.util.Key

/**
 * Generates suggestions for code completion. A simplified version of
 * [com.intellij.codeInsight.completion.CompletionContributor]
 *
 * Instances of this interface are generated by [KindCollector],
 * and then executed
 */

interface SuggestionGenerator {
  /**
   * Kind of completion variants, which will be suggested by this particular generator
   */
  val kind: CompletionKind

  /**
   * Result set, to where the generated completion variants will be stored after
   * [generateCompletionVariants] has been called
   */
  val result: CompletionResultSet

  /**
   * Parameters, which the generated suggestions will be satisfying
   */
  val parameters: CompletionParameters

  /**
   * Generates completion variants, which correspond to [parameters] and puts them
   * to [result]
   */
  fun generateCompletionVariants()

  companion object {
    @JvmStatic
    val LOOKUP_ELEMENT_SUGGESTION_GENERATOR = Key<SuggestionGenerator>("SuggestionGenerator which generated the lookup element")

    @JvmStatic
    fun fromGenerator(kind: CompletionKind,
                      parameters: CompletionParameters,
                      result: CompletionResultSet,
                      generateVariants: () -> Unit): SuggestionGenerator {
      return object : SuggestionGenerator {
        override val kind = kind
        override val result = result
        override val parameters = parameters

        override fun generateCompletionVariants() {
          generateVariants()
        }
      }
    }

    @JvmStatic
    fun withApplicability(kind: CompletionKind,
                          result: CompletionResultSet,
                          parameters: CompletionParameters,
                          generator: () -> Unit,
                          isApplicable: () -> Boolean): SuggestionGenerator {
      return fromGenerator(
        kind,
        parameters,
        result
      ) { if (isApplicable()) generator() else Unit }
    }

    val LookupElement.suggestionGenerator
      get() = this.getUserData(LOOKUP_ELEMENT_SUGGESTION_GENERATOR)
  }
}
