package org.cangnova.cangjie.completion.turboComplete



/**
 * An interface for classes that consume suggestion generators,
 * generated by [KindCollector]
 */

interface SuggestionGeneratorConsumer {
  fun pass(suggestionGenerator: SuggestionGenerator)
}