// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: CangieLexer1.flex

package com.huawei.cangjie1.lexer;

import java.util.*;
import com.intellij.lexer.*;
import com.intellij.psi.*;
import com.intellij.psi.tree.IElementType;
import com.intellij.util.containers.Stack;
import com.huawei.cangjie1.lexer.CangJieLexerException;
import com.huawei.cangjie1.lexer.CjTokens;


class _JetLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int RAW_STRING = 4;
  public static final int SHORT_TEMPLATE_ENTRY = 6;
  public static final int BLOCK_COMMENT = 8;
  public static final int DOC_COMMENT = 10;
  public static final int LONG_TEMPLATE_ENTRY = 12;
  public static final int UNMATCHED_BACKTICK = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  4,  4,  5,  5,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u1f00\1\u3600\1\u3700\1\u3800\1\u3900"+
    "\1\u0100\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000"+
    "\1\u1f00\1\u4100\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700"+
    "\1\u4800\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u1f00\1\u4d00\1\u4e00"+
    "\1\u4f00\1\u1f00\3\u0100\1\u5000\1\u5100\1\u5200\12\u1f00\4\u0100"+
    "\1\u5300\17\u1f00\2\u0100\1\u5400\41\u1f00\2\u0100\1\u5500\1\u5600"+
    "\2\u1f00\1\u5700\1\u5800\27\u0100\1\u5900\2\u0100\1\u5a00\45\u1f00"+
    "\1\u0100\1\u5b00\1\u5c00\11\u1f00\1\u5d00\27\u1f00\1\u5e00\1\u5f00"+
    "\1\u6000\1\u6100\11\u1f00\1\u6200\1\u6300\5\u1f00\1\u6400\1\u6500"+
    "\4\u1f00\1\u6600\21\u1f00\246\u0100\1\u6700\20\u0100\1\u6800\1\u6900"+
    "\25\u0100\1\u6a00\34\u0100\1\u6b00\14\u1f00\2\u0100\1\u6c00\u0e05\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\3\22\0\1\1"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\31\1\33"+
    "\1\31\1\34\1\35\1\36\1\37\1\40\1\41\1\0"+
    "\1\42\1\43\1\44\1\42\1\45\1\46\2\47\1\50"+
    "\2\47\1\51\10\47\1\52\2\47\1\53\2\47\1\54"+
    "\1\55\1\56\1\0\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\47\1\72"+
    "\1\73\1\74\1\75\1\76\1\77\1\47\1\100\1\101"+
    "\1\102\1\103\1\104\1\105\1\53\1\106\1\47\1\107"+
    "\1\110\1\111\7\0\1\3\44\0\1\47\12\0\1\47"+
    "\4\0\1\47\5\0\27\47\1\0\37\47\1\0\u01ca\47"+
    "\4\0\14\47\16\0\5\47\7\0\1\47\1\0\1\47"+
    "\201\0\5\47\1\0\2\47\2\0\4\47\1\0\1\47"+
    "\6\0\1\47\1\0\3\47\1\0\1\47\1\0\24\47"+
    "\1\0\123\47\1\0\213\47\10\0\246\47\1\0\46\47"+
    "\2\0\1\47\6\0\51\47\107\0\33\47\4\0\4\47"+
    "\55\0\53\47\25\0\12\112\4\0\2\47\1\0\143\47"+
    "\1\0\1\47\17\0\2\47\7\0\2\47\12\112\3\47"+
    "\2\0\1\47\20\0\1\47\1\0\36\47\35\0\131\47"+
    "\13\0\1\47\16\0\12\112\41\47\11\0\2\47\4\0"+
    "\1\47\5\0\26\47\4\0\1\47\11\0\1\47\3\0"+
    "\1\47\27\0\31\47\7\0\13\47\65\0\25\47\1\0"+
    "\10\47\106\0\66\47\3\0\1\47\22\0\1\47\7\0"+
    "\12\47\4\0\12\112\1\0\20\47\4\0\10\47\2\0"+
    "\2\47\2\0\26\47\1\0\7\47\1\0\1\47\3\0"+
    "\4\47\3\0\1\47\20\0\1\47\15\0\2\47\1\0"+
    "\3\47\4\0\12\112\2\47\12\0\1\47\10\0\6\47"+
    "\4\0\2\47\2\0\26\47\1\0\7\47\1\0\2\47"+
    "\1\0\2\47\1\0\2\47\37\0\4\47\1\0\1\47"+
    "\7\0\12\112\2\0\3\47\20\0\11\47\1\0\3\47"+
    "\1\0\26\47\1\0\7\47\1\0\2\47\1\0\5\47"+
    "\3\0\1\47\22\0\1\47\17\0\2\47\4\0\12\112"+
    "\11\0\1\47\13\0\10\47\2\0\2\47\2\0\26\47"+
    "\1\0\7\47\1\0\2\47\1\0\5\47\3\0\1\47"+
    "\36\0\2\47\1\0\3\47\4\0\12\112\1\0\1\47"+
    "\21\0\1\47\1\0\6\47\3\0\3\47\1\0\4\47"+
    "\3\0\2\47\1\0\1\47\1\0\2\47\3\0\2\47"+
    "\3\0\3\47\3\0\14\47\26\0\1\47\25\0\12\112"+
    "\25\0\10\47\1\0\3\47\1\0\27\47\1\0\20\47"+
    "\3\0\1\47\32\0\3\47\5\0\2\47\4\0\12\112"+
    "\20\0\1\47\4\0\10\47\1\0\3\47\1\0\27\47"+
    "\1\0\12\47\1\0\5\47\3\0\1\47\40\0\1\47"+
    "\1\0\2\47\4\0\12\112\1\0\2\47\22\0\10\47"+
    "\1\0\3\47\1\0\51\47\2\0\1\47\20\0\1\47"+
    "\5\0\3\47\10\0\3\47\4\0\12\112\12\0\6\47"+
    "\5\0\22\47\3\0\30\47\1\0\11\47\1\0\1\47"+
    "\2\0\7\47\37\0\12\112\21\0\60\47\1\0\2\47"+
    "\14\0\7\47\11\0\12\112\47\0\2\47\1\0\1\47"+
    "\1\0\5\47\1\0\30\47\1\0\1\47\1\0\12\47"+
    "\1\0\2\47\11\0\1\47\2\0\5\47\1\0\1\47"+
    "\11\0\12\112\2\0\4\47\40\0\1\47\37\0\12\112"+
    "\26\0\10\47\1\0\44\47\33\0\5\47\163\0\53\47"+
    "\24\0\1\47\12\112\6\0\6\47\4\0\4\47\3\0"+
    "\1\47\3\0\2\47\7\0\3\47\4\0\15\47\14\0"+
    "\1\47\1\0\12\112\6\0\46\47\1\0\1\47\5\0"+
    "\1\47\2\0\53\47\1\0\115\47\1\0\4\47\2\0"+
    "\7\47\1\0\1\47\1\0\4\47\2\0\51\47\1\0"+
    "\4\47\2\0\41\47\1\0\4\47\2\0\7\47\1\0"+
    "\1\47\1\0\4\47\2\0\17\47\1\0\71\47\1\0"+
    "\4\47\2\0\103\47\45\0\20\47\20\0\126\47\2\0"+
    "\6\47\3\0\u016c\47\2\0\21\47\1\0\32\47\5\0"+
    "\113\47\6\0\10\47\7\0\15\47\1\0\4\47\16\0"+
    "\22\47\16\0\22\47\16\0\15\47\1\0\3\47\17\0"+
    "\64\47\43\0\1\47\4\0\1\47\3\0\12\112\46\0"+
    "\12\112\6\0\131\47\7\0\5\47\2\0\42\47\1\0"+
    "\1\47\5\0\106\47\12\0\37\47\47\0\12\112\36\47"+
    "\2\0\5\47\13\0\54\47\4\0\32\47\6\0\12\112"+
    "\46\0\27\47\11\0\65\47\53\0\12\112\6\0\12\112"+
    "\15\0\1\47\135\0\57\47\21\0\7\47\4\0\12\112"+
    "\51\0\36\47\15\0\2\47\12\112\54\47\32\0\44\47"+
    "\34\0\12\112\3\0\3\47\12\112\44\47\2\0\11\47"+
    "\7\0\53\47\2\0\3\47\51\0\4\47\1\0\6\47"+
    "\1\0\2\47\3\0\1\47\5\0\300\47\100\0\26\47"+
    "\2\0\6\47\2\0\46\47\2\0\6\47\2\0\10\47"+
    "\1\0\1\47\1\0\1\47\1\0\1\47\1\0\37\47"+
    "\2\0\65\47\1\0\7\47\1\0\1\47\3\0\3\47"+
    "\1\0\7\47\3\0\4\47\2\0\6\47\4\0\15\47"+
    "\5\0\3\47\1\0\7\47\53\0\2\3\107\0\1\47"+
    "\15\0\1\47\20\0\15\47\145\0\1\47\4\0\1\47"+
    "\2\0\12\47\1\0\1\47\3\0\5\47\6\0\1\47"+
    "\1\0\1\47\1\0\1\47\1\0\4\47\1\0\13\47"+
    "\2\0\4\47\5\0\5\47\4\0\1\47\64\0\2\47"+
    "\u017b\0\57\47\1\0\57\47\1\0\205\47\6\0\4\47"+
    "\3\0\2\47\14\0\46\47\1\0\1\47\5\0\1\47"+
    "\2\0\70\47\7\0\1\47\20\0\27\47\11\0\7\47"+
    "\1\0\7\47\1\0\7\47\1\0\7\47\1\0\7\47"+
    "\1\0\7\47\1\0\7\47\1\0\7\47\120\0\1\47"+
    "\325\0\2\47\52\0\5\47\5\0\2\47\4\0\126\47"+
    "\6\0\3\47\1\0\132\47\1\0\4\47\5\0\53\47"+
    "\1\0\136\47\21\0\33\47\65\0\306\47\112\0\360\47"+
    "\20\0\215\47\103\0\56\47\2\0\15\47\3\0\20\47"+
    "\12\112\2\47\24\0\57\47\20\0\37\47\2\0\106\47"+
    "\61\0\11\47\2\0\147\47\2\0\65\47\2\0\5\47"+
    "\60\0\13\47\1\0\3\47\1\0\4\47\1\0\27\47"+
    "\35\0\64\47\16\0\62\47\34\0\12\112\30\0\6\47"+
    "\3\0\1\47\1\0\2\47\1\0\12\112\34\47\12\0"+
    "\27\47\31\0\35\47\7\0\57\47\34\0\1\47\12\112"+
    "\6\0\5\47\1\0\12\47\12\112\5\47\1\0\51\47"+
    "\27\0\3\47\1\0\10\47\4\0\12\112\6\0\27\47"+
    "\3\0\1\47\3\0\62\47\1\0\1\47\3\0\2\47"+
    "\2\0\5\47\2\0\1\47\1\0\1\47\30\0\3\47"+
    "\2\0\13\47\7\0\3\47\14\0\6\47\2\0\6\47"+
    "\2\0\6\47\11\0\7\47\1\0\7\47\1\0\53\47"+
    "\1\0\14\47\10\0\163\47\15\0\12\112\6\0\244\47"+
    "\14\0\27\47\4\0\61\47\4\0\u0100\3\156\47\2\0"+
    "\152\47\46\0\7\47\14\0\5\47\5\0\1\47\1\0"+
    "\12\47\1\0\15\47\1\0\5\47\1\0\1\47\1\0"+
    "\2\47\1\0\2\47\1\0\154\47\41\0\153\47\22\0"+
    "\100\47\2\0\66\47\50\0\14\47\164\0\5\47\1\0"+
    "\207\47\23\0\12\112\7\0\32\47\6\0\32\47\13\0"+
    "\131\47\3\0\6\47\2\0\6\47\2\0\6\47\2\0"+
    "\3\47\43\0\14\47\1\0\32\47\1\0\23\47\1\0"+
    "\2\47\1\0\17\47\2\0\16\47\42\0\173\47\205\0"+
    "\35\47\3\0\61\47\57\0\40\47\15\0\24\47\1\0"+
    "\10\47\6\0\46\47\12\0\36\47\2\0\44\47\4\0"+
    "\10\47\60\0\236\47\2\0\12\112\6\0\44\47\4\0"+
    "\44\47\4\0\50\47\10\0\64\47\234\0\67\47\11\0"+
    "\26\47\12\0\10\47\230\0\6\47\2\0\1\47\1\0"+
    "\54\47\1\0\2\47\3\0\1\47\2\0\27\47\12\0"+
    "\27\47\11\0\37\47\101\0\23\47\1\0\2\47\12\0"+
    "\26\47\12\0\32\47\106\0\70\47\6\0\2\47\100\0"+
    "\1\47\17\0\4\47\1\0\3\47\1\0\35\47\52\0"+
    "\35\47\3\0\35\47\43\0\10\47\1\0\34\47\33\0"+
    "\66\47\12\0\26\47\12\0\23\47\15\0\22\47\156\0"+
    "\111\47\67\0\63\47\15\0\63\47\15\0\44\47\14\0"+
    "\12\112\306\0\35\47\12\0\1\47\10\0\26\47\232\0"+
    "\27\47\14\0\65\47\56\0\12\112\23\0\55\47\40\0"+
    "\31\47\7\0\12\112\11\0\44\47\17\0\12\112\4\0"+
    "\1\47\13\0\43\47\3\0\1\47\14\0\60\47\16\0"+
    "\4\47\13\0\12\112\1\47\1\0\1\47\43\0\22\47"+
    "\1\0\31\47\124\0\7\47\1\0\1\47\1\0\4\47"+
    "\1\0\17\47\1\0\12\47\7\0\57\47\21\0\12\112"+
    "\13\0\10\47\2\0\2\47\2\0\26\47\1\0\7\47"+
    "\1\0\2\47\1\0\5\47\3\0\1\47\22\0\1\47"+
    "\14\0\5\47\236\0\65\47\22\0\4\47\5\0\12\112"+
    "\5\0\1\47\40\0\60\47\24\0\2\47\1\0\1\47"+
    "\10\0\12\112\246\0\57\47\51\0\4\47\44\0\60\47"+
    "\24\0\1\47\13\0\12\112\46\0\53\47\15\0\1\47"+
    "\7\0\12\112\66\0\33\47\25\0\12\112\306\0\54\47"+
    "\164\0\100\47\12\112\25\0\1\47\240\0\10\47\2\0"+
    "\47\47\20\0\1\47\1\0\1\47\34\0\1\47\12\0"+
    "\50\47\7\0\1\47\25\0\1\47\13\0\56\47\23\0"+
    "\1\47\42\0\71\47\7\0\11\47\1\0\45\47\21\0"+
    "\1\47\17\0\12\112\30\0\36\47\160\0\7\47\1\0"+
    "\2\47\1\0\46\47\25\0\1\47\11\0\12\112\6\0"+
    "\6\47\1\0\2\47\1\0\40\47\16\0\1\47\7\0"+
    "\12\112\u0136\0\23\47\15\0\232\47\346\0\304\47\274\0"+
    "\57\47\321\0\107\47\271\0\71\47\7\0\37\47\1\0"+
    "\12\112\146\0\36\47\22\0\60\47\20\0\4\47\14\0"+
    "\12\112\11\0\25\47\5\0\23\47\260\0\100\47\200\0"+
    "\113\47\5\0\1\47\102\0\15\47\100\0\2\47\1\0"+
    "\1\47\34\0\370\47\10\0\363\47\15\0\37\47\61\0"+
    "\3\47\21\0\4\47\10\0\u018c\47\4\0\153\47\5\0"+
    "\15\47\3\0\11\47\7\0\12\47\146\0\125\47\1\0"+
    "\107\47\1\0\2\47\2\0\1\47\2\0\2\47\2\0"+
    "\4\47\1\0\14\47\1\0\1\47\1\0\7\47\1\0"+
    "\101\47\1\0\4\47\2\0\10\47\1\0\7\47\1\0"+
    "\34\47\1\0\4\47\1\0\5\47\1\0\1\47\3\0"+
    "\7\47\1\0\u0154\47\2\0\31\47\1\0\31\47\1\0"+
    "\37\47\1\0\31\47\1\0\37\47\1\0\31\47\1\0"+
    "\37\47\1\0\31\47\1\0\37\47\1\0\31\47\1\0"+
    "\10\47\2\0\62\112\55\47\12\0\7\47\2\0\12\112"+
    "\4\0\1\47\u0171\0\54\47\4\0\12\112\6\0\305\47"+
    "\73\0\104\47\7\0\1\47\4\0\12\112\246\0\4\47"+
    "\1\0\33\47\1\0\2\47\1\0\1\47\2\0\1\47"+
    "\1\0\12\47\1\0\4\47\1\0\1\47\1\0\1\47"+
    "\6\0\1\47\4\0\1\47\1\0\1\47\1\0\1\47"+
    "\1\0\3\47\1\0\2\47\1\0\1\47\2\0\1\47"+
    "\1\0\1\47\1\0\1\47\1\0\1\47\1\0\1\47"+
    "\1\0\2\47\1\0\1\47\2\0\4\47\1\0\7\47"+
    "\1\0\4\47\1\0\4\47\1\0\1\47\1\0\12\47"+
    "\1\0\21\47\5\0\3\47\1\0\5\47\1\0\21\47"+
    "\104\0\327\47\51\0\65\47\13\0\336\47\2\0\u0182\47"+
    "\16\0\u0131\47\37\0\36\47\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[27904];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\1\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\2\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\6\27\1\30\1\31\1\32\17\27\1\33\1\1\1\34"+
    "\1\35\1\36\1\37\1\35\1\1\2\35\1\40\1\1"+
    "\1\40\3\41\1\42\1\43\1\44\2\0\1\45\1\46"+
    "\1\0\1\47\1\50\2\7\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\2\0"+
    "\1\20\2\60\3\20\1\64\1\65\1\66\1\67\1\70"+
    "\6\27\1\0\1\71\3\27\1\72\4\27\1\73\1\74"+
    "\1\75\11\27\1\76\1\77\1\0\1\100\2\101\2\0"+
    "\1\40\1\102\1\103\1\0\1\104\1\0\1\105\1\106"+
    "\2\0\1\60\14\27\1\107\2\27\1\110\10\27\1\111"+
    "\1\112\1\27\2\0\1\113\2\40\1\114\1\46\1\115"+
    "\1\116\1\117\4\27\1\120\1\27\1\121\3\27\1\122"+
    "\1\27\1\123\1\27\1\124\4\27\1\125\1\27\1\126"+
    "\1\27\1\77\1\0\1\127\1\27\1\130\1\131\1\132"+
    "\3\27\1\133\1\134\1\135\1\27\1\136\1\27\1\137"+
    "\2\27\1\140\1\141\1\142\1\0\2\27\1\143\1\144"+
    "\1\145\3\27\1\146\1\147\1\150\2\27\1\151\1\152"+
    "\1\27\1\153";

  private static int [] zzUnpackAction() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\113\0\226\0\341\0\u012c\0\u0177\0\u01c2\0\u020d"+
    "\0\u0258\0\u02a3\0\u02ee\0\u0339\0\u0384\0\u03cf\0\u041a\0\u01c2"+
    "\0\u01c2\0\u0465\0\u04b0\0\u01c2\0\u04fb\0\u0546\0\u0591\0\u05dc"+
    "\0\u0627\0\u01c2\0\u0672\0\u06bd\0\u0708\0\u0753\0\u01c2\0\u079e"+
    "\0\u07e9\0\u0834\0\u087f\0\u08ca\0\u0915\0\u01c2\0\u01c2\0\u0960"+
    "\0\u09ab\0\u09f6\0\u0a41\0\u0a8c\0\u0ad7\0\u0b22\0\u0b6d\0\u0bb8"+
    "\0\u0c03\0\u0c4e\0\u0c99\0\u0ce4\0\u0d2f\0\u0d7a\0\u0dc5\0\u01c2"+
    "\0\u0e10\0\u01c2\0\u0e5b\0\u01c2\0\u01c2\0\u0ea6\0\u0ef1\0\u01c2"+
    "\0\u0f3c\0\u0f87\0\u0fd2\0\u101d\0\u01c2\0\u1068\0\u10b3\0\u01c2"+
    "\0\u01c2\0\u01c2\0\u10fe\0\u1149\0\u1194\0\u11df\0\u122a\0\u01c2"+
    "\0\u01c2\0\u01c2\0\u1275\0\u01c2\0\u01c2\0\u01c2\0\u01c2\0\u01c2"+
    "\0\u01c2\0\u01c2\0\u12c0\0\u130b\0\u1356\0\u01c2\0\u13a1\0\u13ec"+
    "\0\u1437\0\u1482\0\u01c2\0\u14cd\0\u1518\0\u1563\0\u01c2\0\u01c2"+
    "\0\u01c2\0\u01c2\0\u01c2\0\u15ae\0\u15f9\0\u1644\0\u168f\0\u16da"+
    "\0\u1725\0\u1770\0\u079e\0\u17bb\0\u1806\0\u1851\0\u079e\0\u189c"+
    "\0\u18e7\0\u1932\0\u197d\0\u079e\0\u19c8\0\u079e\0\u1a13\0\u1a5e"+
    "\0\u1aa9\0\u1af4\0\u1b3f\0\u1b8a\0\u1bd5\0\u1c20\0\u1c6b\0\u01c2"+
    "\0\u1cb6\0\u1d01\0\u01c2\0\u01c2\0\u1d4c\0\u1d97\0\u1de2\0\u1e2d"+
    "\0\u01c2\0\u01c2\0\u1e78\0\u01c2\0\u1ec3\0\u1f0e\0\u01c2\0\u1f59"+
    "\0\u1fa4\0\u1fef\0\u203a\0\u2085\0\u20d0\0\u211b\0\u2166\0\u21b1"+
    "\0\u01c2\0\u21fc\0\u2247\0\u2292\0\u22dd\0\u2328\0\u079e\0\u2373"+
    "\0\u23be\0\u079e\0\u2409\0\u2454\0\u249f\0\u24ea\0\u2535\0\u2580"+
    "\0\u25cb\0\u2616\0\u079e\0\u079e\0\u2661\0\u26ac\0\u26f7\0\u1d97"+
    "\0\u01c2\0\u2742\0\u01c2\0\u01c2\0\u01c2\0\u079e\0\u079e\0\u278d"+
    "\0\u27d8\0\u2823\0\u286e\0\u079e\0\u28b9\0\u079e\0\u2904\0\u294f"+
    "\0\u299a\0\u079e\0\u29e5\0\u079e\0\u2a30\0\u079e\0\u2a7b\0\u2ac6"+
    "\0\u2b11\0\u2b5c\0\u079e\0\u2ba7\0\u079e\0\u2bf2\0\u01c2\0\u2c3d"+
    "\0\u0f87\0\u2c88\0\u079e\0\u079e\0\u079e\0\u2cd3\0\u2d1e\0\u2d69"+
    "\0\u079e\0\u079e\0\u079e\0\u2db4\0\u079e\0\u2dff\0\u079e\0\u2e4a"+
    "\0\u2e95\0\u079e\0\u079e\0\u079e\0\u2ee0\0\u2f2b\0\u2f76\0\u079e"+
    "\0\u079e\0\u079e\0\u2fc1\0\u300c\0\u3057\0\u079e\0\u079e\0\u079e"+
    "\0\u30a2\0\u30ed\0\u079e\0\u079e\0\u3138\0\u079e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\2\10\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\7\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\40\1\43"+
    "\1\40\1\44\1\40\1\45\1\40\1\46\1\7\1\47"+
    "\1\40\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\2\40\1\57\1\40\1\60\1\61\2\40\1\62\1\63"+
    "\1\64\1\65\1\40\1\66\1\67\1\40\1\70\1\71"+
    "\1\72\1\7\2\73\1\74\3\73\1\75\1\73\1\76"+
    "\44\73\1\77\37\73\1\100\3\73\1\101\1\73\1\76"+
    "\44\73\1\100\35\73\2\7\3\0\35\7\12\102\3\7"+
    "\1\102\1\103\21\102\1\104\4\102\4\7\16\105\1\106"+
    "\4\105\1\107\67\105\1\7\2\10\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\7\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\40\1\43\1\40\1\44\1\40\1\45\1\40"+
    "\1\46\1\7\1\47\1\40\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\2\40\1\57\1\40\1\60\1\61"+
    "\2\40\1\62\1\63\1\64\1\65\1\40\1\66\1\67"+
    "\1\40\1\110\1\71\1\111\1\7\114\0\2\10\1\0"+
    "\1\10\145\0\1\112\31\0\1\113\27\0\1\114\111\0"+
    "\1\115\147\0\12\116\3\0\1\116\1\117\26\116\43\0"+
    "\1\120\65\0\1\121\100\0\2\17\1\0\10\17\1\122"+
    "\41\17\1\123\35\17\37\0\1\124\72\0\1\125\17\0"+
    "\1\126\74\0\1\127\15\0\1\130\1\131\74\0\1\132"+
    "\1\0\10\133\75\0\1\134\4\0\1\135\13\0\1\136"+
    "\75\0\1\137\1\0\10\140\7\0\1\141\1\0\1\142"+
    "\1\143\2\0\1\144\1\145\1\146\3\0\1\140\2\0"+
    "\1\141\2\0\1\142\1\143\4\0\1\144\7\0\1\145"+
    "\31\0\1\137\1\0\10\31\11\0\1\142\1\143\2\0"+
    "\1\144\1\145\4\0\1\31\5\0\1\142\1\143\4\0"+
    "\1\144\7\0\1\145\44\0\1\147\114\0\1\150\112\0"+
    "\1\151\1\152\111\0\1\153\77\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\26\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\15\40\1\154\10\40"+
    "\3\0\1\40\24\0\10\40\6\0\12\40\3\0\1\40"+
    "\1\0\7\40\1\155\16\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\12\40\1\156\13\40"+
    "\3\0\1\40\24\0\10\40\6\0\12\40\3\0\1\40"+
    "\1\0\14\40\1\157\11\40\3\0\1\40\24\0\10\40"+
    "\6\0\6\40\1\160\3\40\3\0\1\40\1\0\14\40"+
    "\1\161\11\40\3\0\1\40\2\162\1\0\55\162\1\0"+
    "\32\162\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\20\40\1\163\5\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\17\40\1\164\6\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\12\40\1\165\2\40\1\166\10\40\3\0\1\40\24\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\15\40\1\167"+
    "\10\40\3\0\1\40\24\0\10\40\6\0\12\40\3\0"+
    "\1\40\1\0\12\40\1\170\13\40\3\0\1\40\24\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\1\171\14\40"+
    "\1\172\4\40\1\173\3\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\5\40\1\174\6\40"+
    "\1\175\3\40\1\176\5\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\4\40\1\177\21\40"+
    "\3\0\1\40\24\0\10\40\6\0\12\40\3\0\1\40"+
    "\1\0\1\200\25\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\1\201\25\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\4\40"+
    "\1\202\21\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\22\40\1\203\3\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\7\40"+
    "\1\204\7\40\1\205\6\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\1\206\25\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\7\40\1\207\16\40\3\0\1\40\110\0\1\210\2\0"+
    "\2\73\1\0\3\73\1\0\1\73\1\0\44\73\1\0"+
    "\35\73\42\0\12\211\3\0\1\211\1\212\26\211\1\213"+
    "\3\0\2\214\1\0\100\214\1\215\7\214\6\0\1\216"+
    "\130\0\10\102\6\0\12\102\3\0\1\102\1\0\26\102"+
    "\3\0\1\102\2\217\1\0\55\217\1\0\32\217\24\0"+
    "\10\102\6\0\12\102\3\0\1\102\1\0\7\102\1\220"+
    "\16\102\3\0\1\102\23\0\1\221\105\0\1\222\171\0"+
    "\1\223\3\0\1\223\17\0\1\224\104\0\2\115\1\0"+
    "\110\115\24\0\10\116\6\0\12\116\3\0\1\116\1\0"+
    "\26\116\3\0\1\116\2\225\1\0\55\225\1\0\32\225"+
    "\2\17\1\0\110\17\24\0\10\133\11\0\1\142\1\143"+
    "\10\0\1\133\5\0\1\142\1\143\42\0\1\226\74\0"+
    "\2\135\1\0\110\135\22\0\1\227\1\0\10\133\101\0"+
    "\1\230\1\0\10\140\11\0\1\142\1\143\10\0\1\140"+
    "\5\0\1\142\1\143\46\0\1\231\1\0\10\141\15\0"+
    "\1\144\1\145\4\0\1\141\13\0\1\144\7\0\1\145"+
    "\26\0\1\232\1\0\1\232\2\0\10\232\12\0\1\143"+
    "\10\0\1\232\6\0\1\143\46\0\1\231\112\0\1\231"+
    "\26\0\1\144\21\0\1\144\41\0\1\231\1\0\10\146"+
    "\6\0\5\146\2\0\1\144\1\145\4\0\1\146\1\0"+
    "\6\146\4\0\1\144\7\0\1\145\33\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\15\40\1\233\10\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\1\234\25\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\15\40\1\235\10\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\21\40"+
    "\1\236\4\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\14\40\1\237\11\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\10\40"+
    "\1\240\15\40\3\0\1\40\2\162\1\0\55\162\1\241"+
    "\32\162\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\4\40\1\242\21\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\1\243\25\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\14\40"+
    "\1\244\11\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\20\40\1\245\5\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\12\40"+
    "\1\246\13\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\17\40\1\247\6\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\14\40"+
    "\1\250\11\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\21\40\1\251\4\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\21\40"+
    "\1\252\4\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\10\40\1\253\10\40\1\254\4\40"+
    "\3\0\1\40\24\0\10\40\6\0\12\40\3\0\1\40"+
    "\1\0\2\40\1\255\23\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\21\40\1\256\4\40"+
    "\3\0\1\40\24\0\10\40\6\0\12\40\3\0\1\40"+
    "\1\0\16\40\1\257\7\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\10\40\1\260\6\40"+
    "\1\261\6\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\22\40\1\262\2\40\1\263\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\17\40\1\264\6\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\10\40\1\265\15\40\3\0"+
    "\1\40\24\0\10\211\6\0\12\211\3\0\1\211\1\0"+
    "\26\211\3\0\1\211\2\266\1\0\55\266\1\0\32\266"+
    "\24\0\10\267\6\0\5\267\12\0\6\267\32\0\1\270"+
    "\104\0\2\217\1\0\55\217\1\271\32\217\24\0\10\102"+
    "\6\0\12\102\3\0\1\102\1\0\10\102\1\272\15\102"+
    "\3\0\1\102\24\0\10\273\6\0\12\273\3\0\1\273"+
    "\1\0\26\273\3\0\1\273\2\225\1\0\55\225\1\274"+
    "\32\225\23\0\1\275\113\0\10\133\101\0\1\227\114\0"+
    "\10\232\12\0\1\143\10\0\1\232\6\0\1\143\50\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\12\40\1\276"+
    "\13\40\3\0\1\40\24\0\10\40\6\0\12\40\3\0"+
    "\1\40\1\0\17\40\1\277\6\40\3\0\1\40\24\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\1\300\25\40"+
    "\3\0\1\40\24\0\1\40\1\301\1\40\1\302\2\40"+
    "\1\303\1\304\6\0\12\40\3\0\1\40\1\0\26\40"+
    "\3\0\1\40\24\0\10\40\6\0\12\40\3\0\1\40"+
    "\1\0\21\40\1\305\4\40\3\0\1\40\24\0\10\40"+
    "\6\0\12\40\3\0\1\40\1\0\21\40\1\306\4\40"+
    "\3\0\1\40\24\0\10\40\6\0\12\40\3\0\1\40"+
    "\1\0\1\307\25\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\20\40\1\310\5\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\21\40\1\311\4\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\4\40\1\312\21\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\20\40\1\313\5\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\2\40\1\314\23\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\4\40\1\315\21\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\14\40\1\316\11\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\2\40\1\317\23\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\11\40\1\320\14\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\22\40\1\321\3\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\4\40\1\322\21\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\20\40\1\323\5\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\15\40\1\324\10\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\4\40\1\325\21\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\12\40\1\326\13\40\3\0"+
    "\1\40\2\266\1\0\55\266\1\327\32\266\24\0\10\330"+
    "\6\0\5\330\12\0\6\330\50\0\10\102\6\0\12\102"+
    "\3\0\1\102\1\0\20\102\1\331\5\102\3\0\1\102"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\21\40"+
    "\1\332\4\40\3\0\1\40\24\0\6\40\1\333\1\40"+
    "\6\0\12\40\3\0\1\40\1\0\26\40\3\0\1\40"+
    "\24\0\2\40\1\334\5\40\6\0\12\40\3\0\1\40"+
    "\1\0\26\40\3\0\1\40\24\0\4\40\1\335\3\40"+
    "\6\0\12\40\3\0\1\40\1\0\26\40\3\0\1\40"+
    "\24\0\1\40\1\336\1\40\1\337\2\40\1\340\1\341"+
    "\6\0\12\40\3\0\1\40\1\0\26\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\11\40"+
    "\1\342\14\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\20\40\1\343\5\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\10\40"+
    "\1\344\15\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\4\40\1\345\21\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\17\40"+
    "\1\346\6\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\7\40\1\347\16\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\1\350"+
    "\25\40\3\0\1\40\24\0\10\40\6\0\12\40\3\0"+
    "\1\40\1\0\17\40\1\351\6\40\3\0\1\40\24\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\17\40\1\352"+
    "\6\40\3\0\1\40\24\0\10\40\6\0\12\40\3\0"+
    "\1\40\1\0\24\40\1\353\1\40\3\0\1\40\24\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\4\40\1\354"+
    "\21\40\3\0\1\40\24\0\10\355\6\0\5\355\12\0"+
    "\6\355\50\0\3\40\1\356\2\40\1\357\1\40\6\0"+
    "\12\40\3\0\1\40\1\0\26\40\3\0\1\40\24\0"+
    "\6\40\1\360\1\40\6\0\12\40\3\0\1\40\1\0"+
    "\26\40\3\0\1\40\24\0\2\40\1\361\5\40\6\0"+
    "\12\40\3\0\1\40\1\0\26\40\3\0\1\40\24\0"+
    "\4\40\1\362\3\40\6\0\12\40\3\0\1\40\1\0"+
    "\26\40\3\0\1\40\24\0\10\40\6\0\12\40\3\0"+
    "\1\40\1\0\14\40\1\363\11\40\3\0\1\40\24\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\5\40\1\364"+
    "\20\40\3\0\1\40\24\0\10\40\6\0\12\40\3\0"+
    "\1\40\1\0\6\40\1\365\17\40\3\0\1\40\24\0"+
    "\10\40\6\0\12\40\3\0\1\40\1\0\14\40\1\366"+
    "\11\40\3\0\1\40\24\0\10\214\6\0\5\214\12\0"+
    "\6\214\50\0\2\40\1\367\5\40\6\0\12\40\3\0"+
    "\1\40\1\0\26\40\3\0\1\40\24\0\4\40\1\370"+
    "\3\40\6\0\12\40\3\0\1\40\1\0\26\40\3\0"+
    "\1\40\24\0\10\40\6\0\12\40\3\0\1\40\1\0"+
    "\22\40\1\371\3\40\3\0\1\40\24\0\10\40\6\0"+
    "\12\40\3\0\1\40\1\0\1\372\25\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\4\40"+
    "\1\373\21\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\4\40\1\374\21\40\3\0\1\40"+
    "\24\0\10\40\6\0\12\40\3\0\1\40\1\0\2\40"+
    "\1\375\23\40\3\0\1\40\24\0\10\40\6\0\12\40"+
    "\3\0\1\40\1\0\4\40\1\376\21\40\3\0\1\40";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12675];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\10\1\2\11\2\1\1\11\5\1\1\11"+
    "\4\1\1\11\6\1\2\11\20\1\1\11\1\1\1\11"+
    "\1\1\2\11\2\1\1\11\4\1\1\11\2\1\3\11"+
    "\2\0\2\1\1\0\3\11\1\1\7\11\3\1\1\11"+
    "\2\0\2\1\1\11\3\1\5\11\6\1\1\0\25\1"+
    "\1\11\1\1\1\0\2\11\1\1\2\0\1\1\2\11"+
    "\1\0\1\11\1\0\1\1\1\11\2\0\7\1\1\11"+
    "\24\1\2\0\1\1\1\11\1\1\3\11\31\1\1\11"+
    "\1\0\24\1\1\0\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
 public _JetLexer() {
    this((java.io.Reader)null);}
    private static final class State {
            final int lBraceCount;
            final int state;

            public State(int state, int lBraceCount) {
                this.state = state;
                this.lBraceCount = lBraceCount;
            }

            @Override
            public String toString() {
                return "yystate = " + state + (lBraceCount == 0 ? "" : "lBraceCount = " + lBraceCount);
            }
        }

        private final Stack<State> states = new Stack<State>();
        private int lBraceCount;

        private int commentStart;
        private int commentDepth;

        private void pushState(int state) {
            states.push(new State(yystate(), lBraceCount));
            lBraceCount = 0;
            yybegin(state);
        }

        private void popState() {
            State state = states.pop();
            lBraceCount = state.lBraceCount;
            yybegin(state.state);
        }

        private IElementType commentStateToTokenType(int state) {
            switch (state) {
                case BLOCK_COMMENT:
                    return CjTokens.BLOCK_COMMENT;
                case DOC_COMMENT:
                    return CjTokens.DOC_COMMENT;
                default:
                    throw new IllegalArgumentException("Unexpected state: " + state);
            }
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _JetLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws CangJieLexerException {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new CangJieLexerException(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws CangJieLexerException {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  return;
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException,
     CangJieLexerException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case BLOCK_COMMENT: {
              int state = yystate();
        popState();
        zzStartRead = commentStart;
        return commentStateToTokenType(state);
            }  // fall though
            case 255: break;
            case DOC_COMMENT: {
              int state = yystate();
        popState();
        zzStartRead = commentStart;
        return commentStateToTokenType(state);
            }  // fall though
            case 256: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 108: break;
          case 2:
            { return CjTokens.WHITE_SPACE;
            }
          // fall through
          case 109: break;
          case 3:
            { return CjTokens.EXCL      ;
            }
          // fall through
          case 110: break;
          case 4:
            { pushState(STRING); return CjTokens.OPEN_QUOTE;
            }
          // fall through
          case 111: break;
          case 5:
            { return CjTokens.PERC      ;
            }
          // fall through
          case 112: break;
          case 6:
            { return CjTokens.AND       ;
            }
          // fall through
          case 113: break;
          case 7:
            { return CjTokens.CHARACTER_LITERAL;
            }
          // fall through
          case 114: break;
          case 8:
            { return CjTokens.LPAR      ;
            }
          // fall through
          case 115: break;
          case 9:
            { return CjTokens.RPAR      ;
            }
          // fall through
          case 116: break;
          case 10:
            { return CjTokens.MUL       ;
            }
          // fall through
          case 117: break;
          case 11:
            { return CjTokens.PLUS      ;
            }
          // fall through
          case 118: break;
          case 12:
            { return CjTokens.COMMA     ;
            }
          // fall through
          case 119: break;
          case 13:
            { return CjTokens.MINUS     ;
            }
          // fall through
          case 120: break;
          case 14:
            { return CjTokens.DOT       ;
            }
          // fall through
          case 121: break;
          case 15:
            { return CjTokens.DIV       ;
            }
          // fall through
          case 122: break;
          case 16:
            { return CjTokens.INTEGER_LITERAL;
            }
          // fall through
          case 123: break;
          case 17:
            { return CjTokens.COLON     ;
            }
          // fall through
          case 124: break;
          case 18:
            { return CjTokens.SEMICOLON ;
            }
          // fall through
          case 125: break;
          case 19:
            { return CjTokens.LT        ;
            }
          // fall through
          case 126: break;
          case 20:
            { return CjTokens.EQ        ;
            }
          // fall through
          case 127: break;
          case 21:
            { return CjTokens.GT        ;
            }
          // fall through
          case 128: break;
          case 22:
            { return CjTokens.QUEST     ;
            }
          // fall through
          case 129: break;
          case 23:
            { return CjTokens.IDENTIFIER;
            }
          // fall through
          case 130: break;
          case 24:
            { return CjTokens.LBRACKET  ;
            }
          // fall through
          case 131: break;
          case 25:
            { return CjTokens.RBRACKET  ;
            }
          // fall through
          case 132: break;
          case 26:
            { pushState(UNMATCHED_BACKTICK); return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 133: break;
          case 27:
            { return CjTokens.LBRACE    ;
            }
          // fall through
          case 134: break;
          case 28:
            { return CjTokens.RBRACE    ;
            }
          // fall through
          case 135: break;
          case 29:
            { return CjTokens.REGULAR_STRING_PART;
            }
          // fall through
          case 136: break;
          case 30:
            { popState(); yypushback(1); return CjTokens.DANGLING_NEWLINE;
            }
          // fall through
          case 137: break;
          case 31:
            { popState(); return CjTokens.CLOSING_QUOTE;
            }
          // fall through
          case 138: break;
          case 32:
            { popState(); return CjTokens.IDENTIFIER;
            }
          // fall through
          case 139: break;
          case 33:
            { 
            }
          // fall through
          case 140: break;
          case 34:
            { lBraceCount++; return CjTokens.LBRACE;
            }
          // fall through
          case 141: break;
          case 35:
            { if (lBraceCount == 0) {
                                             popState();
                                             return CjTokens.LONG_TEMPLATE_ENTRY_END;
                                           }
                                           lBraceCount--;
                                           return CjTokens.RBRACE;
            }
          // fall through
          case 142: break;
          case 36:
            { return CjTokens.EXCLEQ    ;
            }
          // fall through
          case 143: break;
          case 37:
            { if (zzCurrentPos == 0) {
                return CjTokens.SHEBANG_COMMENT;
            }
            else {
                yypushback(yylength() - 1);
                return CjTokens.HASH;
            }
            }
          // fall through
          case 144: break;
          case 38:
            { return CjTokens.FIELD_IDENTIFIER;
            }
          // fall through
          case 145: break;
          case 39:
            { return CjTokens.PERCEQ    ;
            }
          // fall through
          case 146: break;
          case 40:
            { return CjTokens.ANDAND    ;
            }
          // fall through
          case 147: break;
          case 41:
            { return CjTokens.MULTEQ    ;
            }
          // fall through
          case 148: break;
          case 42:
            { return CjTokens.PLUSPLUS  ;
            }
          // fall through
          case 149: break;
          case 43:
            { return CjTokens.PLUSEQ    ;
            }
          // fall through
          case 150: break;
          case 44:
            { return CjTokens.MINUSMINUS;
            }
          // fall through
          case 151: break;
          case 45:
            { return CjTokens.MINUSEQ   ;
            }
          // fall through
          case 152: break;
          case 46:
            { return CjTokens.ARROW     ;
            }
          // fall through
          case 153: break;
          case 47:
            { return CjTokens.RANGE     ;
            }
          // fall through
          case 154: break;
          case 48:
            { return CjTokens.FLOAT_LITERAL;
            }
          // fall through
          case 155: break;
          case 49:
            { pushState(BLOCK_COMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
            }
          // fall through
          case 156: break;
          case 50:
            { return CjTokens.EOL_COMMENT;
            }
          // fall through
          case 157: break;
          case 51:
            { return CjTokens.DIVEQ     ;
            }
          // fall through
          case 158: break;
          case 52:
            { return CjTokens.DOUBLE_SEMICOLON;
            }
          // fall through
          case 159: break;
          case 53:
            { return CjTokens.LTEQ      ;
            }
          // fall through
          case 160: break;
          case 54:
            { return CjTokens.EQEQ      ;
            }
          // fall through
          case 161: break;
          case 55:
            { return CjTokens.DOUBLE_ARROW;
            }
          // fall through
          case 162: break;
          case 56:
            { return CjTokens.GTEQ      ;
            }
          // fall through
          case 163: break;
          case 57:
            { return CjTokens.AS_KEYWORD ;
            }
          // fall through
          case 164: break;
          case 58:
            { return CjTokens.DO_KEYWORD ;
            }
          // fall through
          case 165: break;
          case 59:
            { return CjTokens.IF_KEYWORD ;
            }
          // fall through
          case 166: break;
          case 60:
            { return CjTokens.IN_KEYWORD ;
            }
          // fall through
          case 167: break;
          case 61:
            { return CjTokens.IS_KEYWORD ;
            }
          // fall through
          case 168: break;
          case 62:
            { return CjTokens.OROR      ;
            }
          // fall through
          case 169: break;
          case 63:
            { pushState(SHORT_TEMPLATE_ENTRY);
                                                        yypushback(yylength() - 1);
                                                        return CjTokens.SHORT_TEMPLATE_ENTRY_START;
            }
          // fall through
          case 170: break;
          case 64:
            { pushState(LONG_TEMPLATE_ENTRY); return CjTokens.LONG_TEMPLATE_ENTRY_START;
            }
          // fall through
          case 171: break;
          case 65:
            { return CjTokens.ESCAPE_SEQUENCE;
            }
          // fall through
          case 172: break;
          case 66:
            { if (commentDepth > 0) {
            commentDepth--;
        }
        else {
             int state = yystate();
             popState();
             zzStartRead = commentStart;
             return commentStateToTokenType(state);
        }
            }
          // fall through
          case 173: break;
          case 67:
            { commentDepth++;
            }
          // fall through
          case 174: break;
          case 68:
            { pushState(RAW_STRING); return CjTokens.OPEN_QUOTE;
            }
          // fall through
          case 175: break;
          case 69:
            { pushState(DOC_COMMENT);
    commentDepth = 0;
    commentStart = getTokenStart();
            }
          // fall through
          case 176: break;
          case 70:
            { yypushback(2); return CjTokens.INTEGER_LITERAL;
            }
          // fall through
          case 177: break;
          case 71:
            { return CjTokens.FOR_KEYWORD ;
            }
          // fall through
          case 178: break;
          case 72:
            { return CjTokens.LET_KEYWORD ;
            }
          // fall through
          case 179: break;
          case 73:
            { return CjTokens.TRY_KEYWORD ;
            }
          // fall through
          case 180: break;
          case 74:
            { return CjTokens.VAR_KEYWORD ;
            }
          // fall through
          case 181: break;
          case 75:
            { int length = yytext().length();
                                    if (length <= 3) { // closing """
                                        popState();
                                        return CjTokens.CLOSING_QUOTE;
                                    }
                                    else { // some quotes at the end of a string, e.g. """ "foo""""
                                        yypushback(3); // return the closing quotes (""") to the stream
                                        return CjTokens.REGULAR_STRING_PART;
                                    }
            }
          // fall through
          case 182: break;
          case 76:
            { yypushback(3); return CjTokens.EXCL;
            }
          // fall through
          case 183: break;
          case 77:
            { return CjTokens.BLOCK_COMMENT;
            }
          // fall through
          case 184: break;
          case 78:
            { return CjTokens.BOOL_KEYWORD ;
            }
          // fall through
          case 185: break;
          case 79:
            { return CjTokens.CHAR_KEYWORD ;
            }
          // fall through
          case 186: break;
          case 80:
            { return CjTokens.INT8_KEYWORD ;
            }
          // fall through
          case 187: break;
          case 81:
            { return CjTokens.UNIT_KEYWORD ;
            }
          // fall through
          case 188: break;
          case 82:
            { return CjTokens.ELSE_KEYWORD ;
            }
          // fall through
          case 189: break;
          case 83:
            { return CjTokens.FUNC_KEYWORD ;
            }
          // fall through
          case 190: break;
          case 84:
            { return CjTokens.MAIN_KEYWORD ;
            }
          // fall through
          case 191: break;
          case 85:
            { return CjTokens.THIS_KEYWORD ;
            }
          // fall through
          case 192: break;
          case 86:
            { return CjTokens.TRUE_KEYWORD ;
            }
          // fall through
          case 193: break;
          case 87:
            { popState(); return CjTokens.THIS_KEYWORD;
            }
          // fall through
          case 194: break;
          case 88:
            { return CjTokens.INT16_KEYWORD ;
            }
          // fall through
          case 195: break;
          case 89:
            { return CjTokens.INT32_KEYWORD ;
            }
          // fall through
          case 196: break;
          case 90:
            { return CjTokens.INT64_KEYWORD ;
            }
          // fall through
          case 197: break;
          case 91:
            { return CjTokens.UINT8_KEYWORD ;
            }
          // fall through
          case 198: break;
          case 92:
            { return CjTokens.BREAK_KEYWORD ;
            }
          // fall through
          case 199: break;
          case 93:
            { return CjTokens.CLASS_KEYWORD ;
            }
          // fall through
          case 200: break;
          case 94:
            { return CjTokens.FALSE_KEYWORD ;
            }
          // fall through
          case 201: break;
          case 95:
            { return CjTokens.MATCH_KEYWORD ;
            }
          // fall through
          case 202: break;
          case 96:
            { return CjTokens.SUPER_KEYWORD ;
            }
          // fall through
          case 203: break;
          case 97:
            { return CjTokens.THROW_KEYWORD ;
            }
          // fall through
          case 204: break;
          case 98:
            { return CjTokens.WHILE_KEYWORD ;
            }
          // fall through
          case 205: break;
          case 99:
            { return CjTokens.UINT16_KEYWORD ;
            }
          // fall through
          case 206: break;
          case 100:
            { return CjTokens.UINT32_KEYWORD ;
            }
          // fall through
          case 207: break;
          case 101:
            { return CjTokens.UINT64_KEYWORD ;
            }
          // fall through
          case 208: break;
          case 102:
            { return CjTokens.RETURN_KEYWORD ;
            }
          // fall through
          case 209: break;
          case 103:
            { return CjTokens.FLOAT32_KEYWORD ;
            }
          // fall through
          case 210: break;
          case 104:
            { return CjTokens.FLOAT64_KEYWORD ;
            }
          // fall through
          case 211: break;
          case 105:
            { return CjTokens.PACKAGE_KEYWORD ;
            }
          // fall through
          case 212: break;
          case 106:
            { return CjTokens.CONTINUE_KEYWORD ;
            }
          // fall through
          case 213: break;
          case 107:
            { return CjTokens.INTERFACE_KEYWORD ;
            }
          // fall through
          case 214: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
