/*
 * Copyright 2026 LinQingYing. and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * The use of this source code is governed by the Apache License 2.0,
 * which allows users to freely use, modify, and distribute the code,
 * provided they adhere to the terms of the license.
 *
 * The software is provided "as-is", and the authors are not responsible for
 * any damages or issues arising from its use.
 *
 */

package org.cangnova.cangjie.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * KSP 处理器：扫描 @DiagnosticHolder 注解的文件，生成诊断工厂初始化代码
 *
 * 该处理器在编译期执行，自动生成类型安全的初始化代码，替代运行时反射。
 */
class DiagnosticProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    private val diagnosticFactories = mutableListOf<DiagnosticField>()
    private val sourceFiles = mutableSetOf<KSFile>()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        // 查找所有带 @DiagnosticHolder 注解的文件
        val annotatedFiles = resolver.getSymbolsWithAnnotation(
            "org.cangnova.cangjie.diagnostics.DiagnosticHolder"
        ).filterIsInstance<KSFile>()

        for (file in annotatedFiles) {
            logger.info("Processing @DiagnosticHolder file: ${file.fileName}")
            sourceFiles.add(file)  // 记录源文件用于依赖追踪
            processFile(file)
        }

        return emptyList()
    }

    private fun processFile(file: KSFile) {
        // 遍历文件中的所有声明
        file.declarations
            .filterIsInstance<KSPropertyDeclaration>()
            .forEach { property ->
                // 检查是否为顶层属性（没有父类声明）
                if (property.parentDeclaration != null) return@forEach

                val type = property.type.resolve()
                val declaration = type.declaration
                val typeName = declaration.qualifiedName?.asString() ?: return@forEach

                // 调试日志
                logger.info("  Checking property: ${property.simpleName.asString()} of type: $typeName")

                when {
                    // 匹配 DiagnosticFactory 及其子类（DiagnosticFactory0, DiagnosticFactory1, DiagnosticFactory2, etc.）
                    typeName.startsWith("org.cangnova.cangjie.diagnostics.DiagnosticFactory") -> {
                        val name = property.simpleName.asString()
                        val packageName = file.packageName.asString()
                        diagnosticFactories.add(
                            DiagnosticField(
                                name = name,
                                qualifiedName = "$packageName.$name",
                                type = FactoryType.NORMAL
                            )
                        )
                        logger.info("  ✓ Found DiagnosticFactory: $name ($typeName)")
                    }

                    // 匹配 DiagnosticFactoryForDeprecation
                    typeName == "org.cangnova.cangjie.diagnostics.DiagnosticFactoryForDeprecation" -> {
                        val name = property.simpleName.asString()
                        val packageName = file.packageName.asString()
                        diagnosticFactories.add(
                            DiagnosticField(
                                name = name,
                                qualifiedName = "$packageName.$name",
                                type = FactoryType.DEPRECATION
                            )
                        )
                        logger.info("  ✓ Found DiagnosticFactoryForDeprecation: $name")
                    }
                }
            }
    }

    override fun finish() {
        if (diagnosticFactories.isEmpty()) {
            logger.warn("No diagnostic factories found! Make sure files are annotated with @DiagnosticHolder")
            return
        }

        logger.info("Generating initializer for ${diagnosticFactories.size} diagnostic factories")
        generateInitializer()
    }

    private fun generateInitializer() {
        val fileSpec = FileSpec.builder(
            packageName = "org.cangnova.cangjie.diagnostics.generated",
            fileName = "GeneratedDiagnosticInitializer"
        ).apply {
            addFileComment("Generated by KSP - DO NOT EDIT MANUALLY\n")
            addFileComment("This file is automatically regenerated on each build\n")
            addFileComment("\n")
            addFileComment("Total diagnostic factories: ${diagnosticFactories.size}\n")

            // 生成主初始化函数
            addFunction(
                FunSpec.builder("initializeAllDiagnostics")
                    .addKdoc(
                        """
                        初始化所有在 @DiagnosticHolder 文件中找到的诊断工厂。

                        该函数由 KSP 在编译期自动生成。
                        处理了 ${diagnosticFactories.size} 个诊断工厂。

                        生成时间: ${java.time.LocalDateTime.now()}
                        """.trimIndent()
                    )
                    .apply {
                        // 按字母顺序排序以确保生成代码的稳定性
                        diagnosticFactories.sortedBy { it.name }.forEach { field ->
                            when (field.type) {
                                FactoryType.NORMAL -> {
                                    addStatement(
                                        "%L.initializeName(%S)",
                                        field.qualifiedName,
                                        field.name
                                    )
                                }
                                FactoryType.DEPRECATION -> {
                                    addStatement(
                                        "%L.errorFactory.initializeName(%S)",
                                        field.qualifiedName,
                                        "${field.name}_ERROR"
                                    )
                                    addStatement(
                                        "%L.warningFactory.initializeName(%S)",
                                        field.qualifiedName,
                                        "${field.name}_WARNING"
                                    )
                                }
                            }
                        }
                    }
                    .build()
            )

            // 生成统计信息函数
            addFunction(
                FunSpec.builder("getDiagnosticFactoryCount")
                    .addKdoc("返回已初始化的诊断工厂数量")
                    .returns(Int::class)
                    .addStatement("return %L", diagnosticFactories.size)
                    .build()
            )

            // 生成所有工厂名称列表（用于调试）
            addProperty(
                PropertySpec.builder(
                    "allDiagnosticNames",
                    LIST.parameterizedBy(String::class.asTypeName())
                )
                    .addKdoc("所有诊断工厂的名称列表（用于调试）")
                    .initializer(
                        CodeBlock.builder()
                            .add("listOf(\n")
                            .indent()
                            .apply {
                                diagnosticFactories.sortedBy { it.name }.forEachIndexed { index, field ->
                                    if (index > 0) add(",\n")
                                    add("%S", field.name)
                                }
                                add("\n")
                            }
                            .unindent()
                            .add(")")
                            .build()
                    )
                    .build()
            )
        }.build()

        // 使用正确的 API 写入生成的文件
        val dependencies = Dependencies(aggregating = false, *sourceFiles.toTypedArray())
        codeGenerator.createNewFile(
            dependencies = dependencies,
            packageName = "org.cangnova.cangjie.diagnostics.generated",
            fileName = "GeneratedDiagnosticInitializer",
            extensionName = "kt"
        ).bufferedWriter().use { writer ->
            writer.write(fileSpec.toString())
        }

        logger.info("Successfully generated GeneratedDiagnosticInitializer.kt")
    }

    /**
     * 诊断工厂字段信息
     */
    private data class DiagnosticField(
        val name: String,
        val qualifiedName: String,
        val type: FactoryType
    )

    /**
     * 工厂类型
     */
    private enum class FactoryType {
        NORMAL,         // 普通诊断工厂
        DEPRECATION     // 弃用相关的诊断工厂
    }
}
