// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: metadata/src/builtins.proto
// Protobuf Java Version: 4.27.2

package com.huawei.cangjie.metadata.builtins;

public final class BuiltInsProtoBuf {
  private BuiltInsProtoBuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      BuiltInsProtoBuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.packageFqName);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.classAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.constructorAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.functionAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.propertyAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.propertyGetterAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.propertySetterAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.compileTimeValue);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.enumEntryAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.parameterAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.typeAnnotation);
    registry.add(com.huawei.cangjie.metadata.builtins.BuiltInsProtoBuf.typeParameterAnnotation);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int PACKAGE_FQ_NAME_FIELD_NUMBER = 151;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Package { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Package,
      java.lang.Integer> packageFqName = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int CLASS_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Class { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Class,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> classAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int CONSTRUCTOR_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Constructor { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Constructor,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> constructorAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int FUNCTION_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Function { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Function,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> functionAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int PROPERTY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Property,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> propertyAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int PROPERTY_GETTER_ANNOTATION_FIELD_NUMBER = 152;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Property,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> propertyGetterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int PROPERTY_SETTER_ANNOTATION_FIELD_NUMBER = 153;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Property,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> propertySetterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int COMPILE_TIME_VALUE_FIELD_NUMBER = 151;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Property { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Property,
      com.huawei.cangjie.metadata.ProtoBuf.Annotation.Argument.Value> compileTimeValue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.Argument.Value.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.Argument.Value.getDefaultInstance());
  public static final int ENUM_ENTRY_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.EnumEntry { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.EnumEntry,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> enumEntryAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.ValueParameter { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.ValueParameter,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> parameterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int TYPE_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.Type { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.Type,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> typeAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());
  public static final int TYPE_PARAMETER_ANNOTATION_FIELD_NUMBER = 150;
  /**
   * <code>extend .com.huawei.cangjie.metadata.TypeParameter { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.huawei.cangjie.metadata.ProtoBuf.TypeParameter,
      java.util.List<com.huawei.cangjie.metadata.ProtoBuf.Annotation>> typeParameterAnnotation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.class,
        com.huawei.cangjie.metadata.ProtoBuf.Annotation.getDefaultInstance());

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033metadata/src/builtins.proto\022$com.huawe" +
      "i.cangjie.metadata.builtins\032\033metadata/sr" +
      "c/metadata.proto:>\n\017package_fq_name\022$.co" +
      "m.huawei.cangjie.metadata.Package\030\227\001 \001(\005" +
      ":f\n\020class_annotation\022\".com.huawei.cangji" +
      "e.metadata.Class\030\226\001 \003(\0132\'.com.huawei.can" +
      "gjie.metadata.Annotation:r\n\026constructor_" +
      "annotation\022(.com.huawei.cangjie.metadata" +
      ".Constructor\030\226\001 \003(\0132\'.com.huawei.cangjie" +
      ".metadata.Annotation:l\n\023function_annotat" +
      "ion\022%.com.huawei.cangjie.metadata.Functi" +
      "on\030\226\001 \003(\0132\'.com.huawei.cangjie.metadata." +
      "Annotation:l\n\023property_annotation\022%.com." +
      "huawei.cangjie.metadata.Property\030\226\001 \003(\0132" +
      "\'.com.huawei.cangjie.metadata.Annotation" +
      ":s\n\032property_getter_annotation\022%.com.hua" +
      "wei.cangjie.metadata.Property\030\230\001 \003(\0132\'.c" +
      "om.huawei.cangjie.metadata.Annotation:s\n" +
      "\032property_setter_annotation\022%.com.huawei" +
      ".cangjie.metadata.Property\030\231\001 \003(\0132\'.com." +
      "huawei.cangjie.metadata.Annotation:z\n\022co" +
      "mpile_time_value\022%.com.huawei.cangjie.me" +
      "tadata.Property\030\227\001 \001(\01326.com.huawei.cang" +
      "jie.metadata.Annotation.Argument.Value:o" +
      "\n\025enum_entry_annotation\022&.com.huawei.can" +
      "gjie.metadata.EnumEntry\030\226\001 \003(\0132\'.com.hua" +
      "wei.cangjie.metadata.Annotation:s\n\024param" +
      "eter_annotation\022+.com.huawei.cangjie.met" +
      "adata.ValueParameter\030\226\001 \003(\0132\'.com.huawei" +
      ".cangjie.metadata.Annotation:d\n\017type_ann" +
      "otation\022!.com.huawei.cangjie.metadata.Ty" +
      "pe\030\226\001 \003(\0132\'.com.huawei.cangjie.metadata." +
      "Annotation:w\n\031type_parameter_annotation\022" +
      "*.com.huawei.cangjie.metadata.TypeParame" +
      "ter\030\226\001 \003(\0132\'.com.huawei.cangjie.metadata" +
      ".AnnotationB\022B\020BuiltInsProtoBuf"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.huawei.cangjie.metadata.ProtoBuf.getDescriptor(),
        });
    packageFqName.internalInit(descriptor.getExtensions().get(0));
    classAnnotation.internalInit(descriptor.getExtensions().get(1));
    constructorAnnotation.internalInit(descriptor.getExtensions().get(2));
    functionAnnotation.internalInit(descriptor.getExtensions().get(3));
    propertyAnnotation.internalInit(descriptor.getExtensions().get(4));
    propertyGetterAnnotation.internalInit(descriptor.getExtensions().get(5));
    propertySetterAnnotation.internalInit(descriptor.getExtensions().get(6));
    compileTimeValue.internalInit(descriptor.getExtensions().get(7));
    enumEntryAnnotation.internalInit(descriptor.getExtensions().get(8));
    parameterAnnotation.internalInit(descriptor.getExtensions().get(9));
    typeAnnotation.internalInit(descriptor.getExtensions().get(10));
    typeParameterAnnotation.internalInit(descriptor.getExtensions().get(11));
    descriptor.resolveAllFeaturesImmutable();
    com.huawei.cangjie.metadata.ProtoBuf.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
