version: '1.0'
name: pipeline-20250111
displayName: 构建插件
triggers:
  trigger: auto
  push:
    branches:
      # 监听特定分支进行构建
      prefix:
        - 'analyze'         # 仅监听 analyze 分支


stages:
  - setup
  - build

variables:
  GRADLE_USER_HOME: /cache/gradle

cache:
  paths:
    - $GRADLE_USER_HOME

before_script:
  # 确保 Gradle Wrapper 脚本有执行权限
  - chmod +x ./gradlew

build_intellij_plugin:
  stage: build
  script:
    # 清理旧的构建文件
    - ./gradlew clean
    # 构建 IntelliJ 插件
    - ./gradlew buildPlugin
  artifacts:
    # 存储构建生成的插件 zip 文件
    paths:
      - build/distributions/*.zip
