package com.huawei.cangjie.analyzer.api

import com.huawei.cangjie.analyzer.CjAnalysisSession
import com.huawei.cangjie.analyzer.lifetime.CjLifetimeOwner
import com.intellij.psi.PsiElement

public interface CjSymbol : CjLifetimeOwner {
    public val origin: CjSymbolOrigin

    /**
     * [PsiElement] which corresponds to given [CjSymbol]
     * If [origin] is one of [CjSymbolOrigin.SOURCE], [CjSymbolOrigin.JAVA], [CjSymbolOrigin.LIBRARY] then the source is not null
     * For other [CjSymbolOrigin] behaviour is undefined
     *
     * For [CjSymbolOrigin.LIBRARY] the generated by CangJie class file source element is returned
     */
    public val psi: PsiElement?

    context(CjAnalysisSession)
    public fun createPointer(): CjSymbolPointer<CjSymbol>
}
/**
 * A place where [CjSymbol] came from
 */
public enum class CjSymbolOrigin {
    /**
     * Declaration from CangJie sources
     */
    SOURCE,

    /**
     * Declaration which do not have its PSI source and was generated, they are:
     * For regular classes, implicit default constructor is generated
     * For data classes the `copy`, `component{N}`, `toString`, `equals`, `hashCode` functions are generated
     * For enum classes the `valueOf` & `values` functions are generated
     * For lambda the `it` implicit parameter is generated
     */
    SOURCE_MEMBER_GENERATED,

    /**
     * A CangJie declaration came from some .class file
     */
    LIBRARY,


    /**
     * A synthetic function that is called as a lambda argument when creating a SAM interface object, e.g.,
     * ```
     * val isEven = <caret>IntPredicate { it % 2 == 0 }
     * ```
     */
    SAM_CONSTRUCTOR,

    /**
     * Consider the following code:
     * ```
     * interface A { fun x() }
     * interface B { fun x() }
     *
     * interface C : A, B
     * ```
     * The intersection of functions A.foo & B.foo will create a function C.foo which will be marked with [INTERSECTION_OVERRIDE]
     */
    INTERSECTION_OVERRIDE,

    /**
     * Consider the following code:
     * ```
     * interface A<T> { fun x(): T }
     * interface B : A<Int> { }
     * ```
     *
     * The B will have a member B.foo(): Int, this member is generated inside interface B with substitution T -> Int,
     * such members are SUBSTITUTION_OVERRIDE
     */
    SUBSTITUTION_OVERRIDE,

    /**
     * Member symbol which was generated by compiler when using `by` interface delegation
     * e.g,
     * ```
     * interface A { fun x() }
     * class B(a: A) : A by a
     * ```
     * the `B.foo` function will be generated by CangJie compiler
     */
    DELEGATED,



    /**
     * Declaration is backing field of some member property
     * A symbol kind of [CjBackingFieldSymbol]
     *
     * @see CjBackingFieldSymbol
     */
    PROPERTY_BACKING_FIELD,

    /**
     * Declaration generated by the compiler plugin.
     *
     * @see org.jetbrains.kotlin.fir.declarations.FirDeclarationOrigin.Plugin
     */
    PLUGIN,


}
