// 顶部注释块，包含自定义的解析器类、元素类型持有类及 PSI 类相关配置信息
{
    parserClass='com.linqingying.cangjie.grammar.parser.CangJieParser'
    elementTypeHolderClass='com.linqingying.cangjie.grammar.psi.CjElementTypes'
    psiClassPrefix='Cj'
    psiImplClassSuffix='Impl'
    parserUtilClass='com.linqingying.cangjie.grammar.psi.CangJieParserUtil'

    psiPackage='com.linqingying.cangjie.grammar.psi'
    psiImplPackage='com.linqingying.cangjie.grammar.psi.impl'
 tokenTypeClass="com.linqingying.cangjie.lexer.CjToken"

    implements='com.linqingying.cangjie.psi.CjElement'
    extends='com.linqingying.cangjie.psi.CjElementImpl'


    tokens=[
    /*********************************关键字定义*****************************************/
        INT8               = 'Int8';
        INT16              = 'Int16';
        INT32              = 'Int32';
        INT64              = 'Int64';
        INTNATIVE          = 'IntNative';
        UINT8              = 'UInt8';
        UINT16             = 'UInt16';
        UINT32             = 'UInt32';
        UINT64             = 'UInt64';
        UINTNATIVE         = 'UIntNative';
        FLOAT16            = 'Float16';
        FLOAT32            = 'Float32';
        FLOAT64            = 'Float64';
        CHAR               = 'Char';
        BOOLEAN            = 'Bool';
        UNIT               = 'Unit';
        NOTHING            = 'Nothing';
        STRUCT             = 'struct';
        ENUM               = 'enum';
        THISTYPE           = 'This';
        PACKAGE            = 'package';
        IMPORT             = 'import';
        CLASS              = 'class';
        INTERFACE          = 'interface';
        FUNC               = 'func';
        MAIN               = 'main';
        LET                = 'let';
        VAR                = 'var';
        CONST              = 'const';
        TYPE_ALIAS         = 'type';
        INIT               = 'init';
        THIS               = 'this';
        SUPER              = 'super';

        // 控制流和条件结构关键字
        IF                 = 'if';
        ELSE               = 'else';
        CASE               = 'case';
        TRY                = 'try';
        CATCH              = 'catch';
        FINALLY            = 'finally';
        FOR                = 'for';
        DO                 = 'do';
        WHILE              = 'while';
        THROW              = 'throw';
        RETURN             = 'return';
        CONTINUE           = 'continue';
        BREAK              = 'break';
        IS                 = 'is';
        AS                 = 'as';
        IN                 = 'in';
        MATCH              = 'match';
        FROM               = 'from';
        WHERE              = 'where';

        // 类型和成员修饰符
        EXTEND             = 'extend';
        SPAWN              = 'spawn';
        SYNCHRONIZED       = 'synchronized';
        MACRO              = 'macro';
        QUOTE              = 'quote';
        TRUE               = 'true';
        FALSE              = 'false';
        STATIC             = 'static';
        PUBLIC             = 'public';
        PRIVATE            = 'private';
        PROTECTED          = 'protected';
        OVERRIDE           = 'override';
        REDEF              = 'redef';
        ABSTRACT           = 'abstract';
        OPEN               = 'open';
        OPERATOR           = 'operator';
        FOREIGN            = 'foreign';
        INOUT              = 'inout';
        PROP               = 'prop';
        MUT                = 'mut';
        UNSAFE             = 'unsafe';
        GET                = 'get';
        SET                = 'set';



        /*********************************符号*****************************************/
        DOT                = '.';
        COMMA              = ',';
        LPAREN             = '(';
        RPAREN             = ')';
        LSQUARE            = '[';
        RSQUARE            = ']';
        LCURL              = '{';
        RCURL              = '}';
        EXP                = '**';
        MUL                = '*';
        MOD                = '%';
        DIV                = '/';
        ADD                = '+';
        SUB                = '-';
        PIPELINE           = '|>';
        COMPOSITION        = '~>';
        INC                = '++';
        DEC                = '--';
        AND                = '&&';
        OR                 = '||';
        NOT                = '!';
        BITAND             = '&';
        BITOR              = '|';
        BITXOR             = '^';
        LSHIFT             = '<<';
        RSHIFT             = '>>';
        COLON              = ':';
        SEMI               = ';';
        ASSIGN             = '=';
        ADD_ASSIGN         = '+=';
        SUB_ASSIGN         = '-=';
        MUL_ASSIGN         = '*=';
        EXP_ASSIGN         = '**=';
        DIV_ASSIGN         = '/=';
        MOD_ASSIGN         = '%=';
        AND_ASSIGN         = '&&=';
        OR_ASSIGN          = '||=';
        BITAND_ASSIGN      = '&=';
        BITOR_ASSIGN       = '|=';
        BITXOR_ASSIGN      = '^=';
        LSHIFT_ASSIGN      = '<<=';
        RSHIFT_ASSIGN      = '>>=';
        ARROW              = '->';
        BACKARROW          = '<-';
        DOUBLE_ARROW       = '=>';
        ELLIPSIS           = '...';
        CLOSEDRANGEOP      = '..=';
        RANGEOP            = '..';
        HASH               = '#';
        AT                 = '@';
        QUEST              = '?';
        UPPERBOUND         = '<:';
        LT                 = '<';
        GT                 = '>';
        LE                 = '<=';
        GE                 = '>=';
        NOTEQUAL           = '!=';
        EQUAL              = '==';
        WILDCARD           = '_';
        BACKSLASH          = '\\';
        QUOTESYMBOL        = '`';
        DOLLAR             = '$';
        QUOTE_OPEN         = '"';
        TRIPLE_QUOTE_OPEN  = '"""';
//        QUOTE_CLOSE        = '"';
//        TRIPLE_QUOTE_CLOSE = '"""';
        LineStrExprStart   = '${';
//        MultiLineStrExprStart = '${';
    ]

}

// 文档前导部分（如包声明等）

//Abc ::= abc abc abc Abcd
//Abcd ::= abcde
File ::= preamble?

preamble
  ::= packageHeader?



packageHeader
  ::= package NL*  packageName end+

packageName
  ::= identifier  (  DOT   identifier)*


importList  ::= (FROM   identifier)?  IMPORT  importAllOrSpecified
    (  COMMA   importAllOrSpecified)* end?
    {
    extends="com.linqingying.cangjie.psi.CjElementImplStub<?>"
    stubClass = "com.linqingying.cangjie.psi.stubs.CangJiePlaceHolderStub<?>"
    }




importAllOrSpecified
  ::= (importAll
        | importSpecified)  importAlias?


importSpecified
  ::=  (identifier   DOT  )+ identifier


importAll
  ::=  (identifier   DOT  )+ MUL


importAlias
 ::=  AS   identifier


end ::=NL |  ';'


WS ::=  (  ' '  |  '\t'  |  '\n'  |  '\r'  |  '\u000C'  )+
NL ::= '\n' | '\r\n'
;

// 注意：这里没有给出后续的语法规则，实际情况下应继续定义程序的其他语法结构，例如变量声明、函数定义、类与接口定义等等。
