name: Build

on:
  push:
    branches: [ main, master, psi ]
  pull_request:
    branches: [ main, master, psi ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 确保gradlew有执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 下载并设置Linux版的FlatBuffers编译器
      - name: Download and setup FlatBuffers compiler
        run: |
          mkdir -p metadata/flatbuffers  # 确保目录存在
          wget https://github.com/google/flatbuffers/releases/download/v25.2.10/Linux.flatc.binary.clang++-18.zip -O metadata/flatbuffers/flatc
          chmod +x metadata/flatbuffers/flatc  # 添加执行权限

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Build Plugin
        run: ./gradlew buildPlugin